#pragma once

#define STB_IMAGE_STATIC
#define STB_IMAGE_IMPLEMENTATION
#define STBI_FAILURE_USERMSG

#include <stb_image.h>

#undef STB_IMAGE_STATIC
#undef STB_IMAGE_IMPLEMENTATION
#undef STBI_FAILURE_USERMSG

