#define GL_LOADER_WANT_LEGACY_TYPES
#include "gl.hh"
#undef GL_LOADER_WANT_LEGACY_TYPES

using namespace gl::types;
#if defined(__APPLE__)
#include <dlfcn.h>

static void* AppleGLGetProcAddress (char const* name)
{
	static void* image = NULL;

	if (NULL == image)
		image = dlopen("/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL", RTLD_LAZY);

	return (image ? dlsym(image, name) : NULL);
}
#endif /* __APPLE__ */

#if defined(__sgi) || defined (__sun)
#include <dlfcn.h>
#include <stdio.h>

static void* SunGetProcAddress (ubyte_type const* name)
{
  static void* h = NULL;
  static void* gpa;

  if (h == NULL)
  {
    if ((h = dlopen(NULL, RTLD_LAZY | RTLD_LOCAL)) == NULL) return NULL;
    gpa = dlsym(h, "glXGetProcAddress");
  }

  if (gpa != NULL)
    return ((void*(*)(ubyte_type const*))gpa)(name);
  else
    return dlsym(h, (char const*)name);
}
#endif /* __sgi || __sun */

#if defined(_WIN32)

#ifdef _MSC_VER
#pragma warning(disable: 4055)
#pragma warning(disable: 4054)
#pragma warning(disable: 4996)
#endif

static int TestPointer(const PROC pTest)
{
	ptrdiff_t iTest;
	if(!pTest) return 0;
	iTest = (ptrdiff_t)pTest;

	if(iTest == 1 || iTest == 2 || iTest == 3 || iTest == -1) return 0;

	return 1;
}

static PROC WinGetProcAddress(char const* name)
{
	HMODULE glMod = NULL;
	PROC pFunc = wglGetProcAddress((LPCSTR)name);
	if(TestPointer(pFunc))
	{
		return pFunc;
	}
	glMod = GetModuleHandleA("Open32_type.dll");
	return (PROC)GetProcAddress(glMod, (LPCSTR)name);
}

#define IntGetProcAddress(name) WinGetProcAddress(name)
#else
	#if defined(__APPLE__)
		#define IntGetProcAddress(name) AppleGLGetProcAddress(name)
	#else
		#if defined(__sgi) || defined(__sun)
			#define IntGetProcAddress(name) SunGetProcAddress(name)
		#else /* GLX */
		    #include <GL/glx.h>

			#define IntGetProcAddress(name) (*glXGetProcAddressARB)((ubyte_type const*)name)
		#endif
	#endif
#endif

namespace gl
{
	namespace funcs
	{
		#define DEFINE_API(RESULT, VAR, ARGS...) \
			using VAR##_type = RESULT (ARGS); \
			VAR##_type* VAR
		DEFINE_API(void, blend_func, enum_type, enum_type);
		DEFINE_API(void, clear, bitfield_type);
		DEFINE_API(void, clear_color, float_type, float_type, float_type, float_type);
		DEFINE_API(void, clear_depth, double_type);
		DEFINE_API(void, clear_stencil, int_type);
		DEFINE_API(void, color_mask, boolean_type, boolean_type, boolean_type, boolean_type);
		DEFINE_API(void, cull_face, enum_type);
		DEFINE_API(void, depth_func, enum_type);
		DEFINE_API(void, depth_mask, boolean_type);
		DEFINE_API(void, depth_range, double_type, double_type);
		DEFINE_API(void, disable, enum_type);
		DEFINE_API(void, draw_buffer, enum_type);
		DEFINE_API(void, enable, enum_type);
		DEFINE_API(void, finish, void);
		DEFINE_API(void, flush, void);
		DEFINE_API(void, front_face, enum_type);
		DEFINE_API(void, get_booleanv, enum_type, boolean_type *);
		DEFINE_API(void, get_doublev, enum_type, double_type *);
		DEFINE_API(enum_type, get_error, void);
		DEFINE_API(void, get_floatv, enum_type, float_type *);
		DEFINE_API(void, get_integerv, enum_type, int_type *);
		DEFINE_API(ubyte_type const*, get_string, enum_type);
		DEFINE_API(void, get_tex_image, enum_type, int_type, enum_type, enum_type, void *);
		DEFINE_API(void, get_tex_level_parameterfv, enum_type, int_type, enum_type, float_type *);
		DEFINE_API(void, get_tex_level_parameteriv, enum_type, int_type, enum_type, int_type *);
		DEFINE_API(void, get_tex_parameterfv, enum_type, enum_type, float_type *);
		DEFINE_API(void, get_tex_parameteriv, enum_type, enum_type, int_type *);
		DEFINE_API(void, hint, enum_type, enum_type);
		DEFINE_API(boolean_type, is_enabled, enum_type);
		DEFINE_API(void, line_width, float_type);
		DEFINE_API(void, logic_op, enum_type);
		DEFINE_API(void, pixel_storef, enum_type, float_type);
		DEFINE_API(void, pixel_storei, enum_type, int_type);
		DEFINE_API(void, point_size, float_type);
		DEFINE_API(void, polygon_mode, enum_type, enum_type);
		DEFINE_API(void, read_buffer, enum_type);
		DEFINE_API(void, read_pixels, int_type, int_type, sizei_type, sizei_type, enum_type, enum_type, void *);
		DEFINE_API(void, scissor, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, stencil_func, enum_type, int_type, uint_type);
		DEFINE_API(void, stencil_mask, uint_type);
		DEFINE_API(void, stencil_op, enum_type, enum_type, enum_type);
		DEFINE_API(void, tex_image1d, enum_type, int_type, int_type, sizei_type, int_type, enum_type, enum_type, void const*);
		DEFINE_API(void, tex_image2d, enum_type, int_type, int_type, sizei_type, sizei_type, int_type, enum_type, enum_type, void const*);
		DEFINE_API(void, tex_parameterf, enum_type, enum_type, float_type);
		DEFINE_API(void, tex_parameterfv, enum_type, enum_type, float_type const*);
		DEFINE_API(void, tex_parameteri, enum_type, enum_type, int_type);
		DEFINE_API(void, tex_parameteriv, enum_type, enum_type, int_type const*);
		DEFINE_API(void, viewport, int_type, int_type, sizei_type, sizei_type);

		DEFINE_API(void, bind_texture, enum_type, uint_type);
		DEFINE_API(void, copy_tex_image1d, enum_type, int_type, enum_type, int_type, int_type, sizei_type, int_type);
		DEFINE_API(void, copy_tex_image2d, enum_type, int_type, enum_type, int_type, int_type, sizei_type, sizei_type, int_type);
		DEFINE_API(void, copy_tex_sub_image1d, enum_type, int_type, int_type, int_type, int_type, sizei_type);
		DEFINE_API(void, copy_tex_sub_image2d, enum_type, int_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, delete_textures, sizei_type, uint_type const*);
		DEFINE_API(void, draw_arrays, enum_type, int_type, sizei_type);
		DEFINE_API(void, draw_elements, enum_type, sizei_type, enum_type, void const*);
		DEFINE_API(void, gen_textures, sizei_type, uint_type *);
		DEFINE_API(void, get_pointerv, enum_type, void **);
		DEFINE_API(boolean_type, is_texture, uint_type);
		DEFINE_API(void, polygon_offset, float_type, float_type);
		DEFINE_API(void, tex_sub_image1d, enum_type, int_type, int_type, sizei_type, enum_type, enum_type, void const*);
		DEFINE_API(void, tex_sub_image2d, enum_type, int_type, int_type, int_type, sizei_type, sizei_type, enum_type, enum_type, void const*);

		DEFINE_API(void, copy_tex_sub_image3d, enum_type, int_type, int_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, draw_range_elements, enum_type, uint_type, uint_type, sizei_type, enum_type, void const*);
		DEFINE_API(void, tex_image3d, enum_type, int_type, int_type, sizei_type, sizei_type, sizei_type, int_type, enum_type, enum_type, void const*);
		DEFINE_API(void, tex_sub_image3d, enum_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, enum_type, enum_type, void const*);

		DEFINE_API(void, active_texture, enum_type);
		DEFINE_API(void, compressed_tex_image1d, enum_type, int_type, enum_type, sizei_type, int_type, sizei_type, void const*);
		DEFINE_API(void, compressed_tex_image2d, enum_type, int_type, enum_type, sizei_type, sizei_type, int_type, sizei_type, void const*);
		DEFINE_API(void, compressed_tex_image3d, enum_type, int_type, enum_type, sizei_type, sizei_type, sizei_type, int_type, sizei_type, void const*);
		DEFINE_API(void, compressed_tex_sub_image1d, enum_type, int_type, int_type, sizei_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, compressed_tex_sub_image2d, enum_type, int_type, int_type, int_type, sizei_type, sizei_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, compressed_tex_sub_image3d, enum_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, get_compressed_tex_image, enum_type, int_type, void *);
		DEFINE_API(void, sample_coverage, float_type, boolean_type);

		DEFINE_API(void, blend_color, float_type, float_type, float_type, float_type);
		DEFINE_API(void, blend_equation, enum_type);
		DEFINE_API(void, blend_func_separate, enum_type, enum_type, enum_type, enum_type);
		DEFINE_API(void, multi_draw_arrays, enum_type, int_type const*, sizei_type const*, sizei_type);
		DEFINE_API(void, multi_draw_elements, enum_type, sizei_type const*, enum_type, void const* const*, sizei_type);
		DEFINE_API(void, point_parameterf, enum_type, float_type);
		DEFINE_API(void, point_parameterfv, enum_type, float_type const*);
		DEFINE_API(void, point_parameteri, enum_type, int_type);
		DEFINE_API(void, point_parameteriv, enum_type, int_type const*);

		DEFINE_API(void, begin_query, enum_type, uint_type);
		DEFINE_API(void, bind_buffer, enum_type, uint_type);
		DEFINE_API(void, buffer_data, enum_type, sizeiptr_type, void const*, enum_type);
		DEFINE_API(void, buffer_sub_data, enum_type, intptr_type, sizeiptr_type, void const*);
		DEFINE_API(void, delete_buffers, sizei_type, uint_type const*);
		DEFINE_API(void, delete_queries, sizei_type, uint_type const*);
		DEFINE_API(void, end_query, enum_type);
		DEFINE_API(void, gen_buffers, sizei_type, uint_type *);
		DEFINE_API(void, gen_queries, sizei_type, uint_type *);
		DEFINE_API(void, get_buffer_parameteriv, enum_type, enum_type, int_type *);
		DEFINE_API(void, get_buffer_pointerv, enum_type, enum_type, void **);
		DEFINE_API(void, get_buffer_sub_data, enum_type, intptr_type, sizeiptr_type, void *);
		DEFINE_API(void, get_query_objectiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_query_objectuiv, uint_type, enum_type, uint_type *);
		DEFINE_API(void, get_queryiv, enum_type, enum_type, int_type *);
		DEFINE_API(boolean_type, is_buffer, uint_type);
		DEFINE_API(boolean_type, is_query, uint_type);
		DEFINE_API(void *, map_buffer, enum_type, enum_type);
		DEFINE_API(boolean_type, unmap_buffer, enum_type);

		DEFINE_API(void, attach_shader, uint_type, uint_type);
		DEFINE_API(void, bind_attrib_location, uint_type, uint_type, char_type const*);
		DEFINE_API(void, blend_equation_separate, enum_type, enum_type);
		DEFINE_API(void, compile_shader, uint_type);
		DEFINE_API(uint_type, create_program, void);
		DEFINE_API(uint_type, create_shader, enum_type);
		DEFINE_API(void, delete_program, uint_type);
		DEFINE_API(void, delete_shader, uint_type);
		DEFINE_API(void, detach_shader, uint_type, uint_type);
		DEFINE_API(void, disable_vertex_attrib_array, uint_type);
		DEFINE_API(void, draw_buffers, sizei_type, enum_type const*);
		DEFINE_API(void, enable_vertex_attrib_array, uint_type);
		DEFINE_API(void, get_active_attrib, uint_type, uint_type, sizei_type, sizei_type *, int_type *, enum_type *, char_type *);
		DEFINE_API(void, get_active_uniform, uint_type, uint_type, sizei_type, sizei_type *, int_type *, enum_type *, char_type *);
		DEFINE_API(void, get_attached_shaders, uint_type, sizei_type, sizei_type *, uint_type *);
		DEFINE_API(int_type, get_attrib_location, uint_type, char_type const*);
		DEFINE_API(void, get_program_info_log, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_programiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_shader_info_log, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_shader_source, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_shaderiv, uint_type, enum_type, int_type *);
		DEFINE_API(int_type, get_uniform_location, uint_type, char_type const*);
		DEFINE_API(void, get_uniformfv, uint_type, int_type, float_type *);
		DEFINE_API(void, get_uniformiv, uint_type, int_type, int_type *);
		DEFINE_API(void, get_vertex_attrib_pointerv, uint_type, enum_type, void **);
		DEFINE_API(void, get_vertex_attribdv, uint_type, enum_type, double_type *);
		DEFINE_API(void, get_vertex_attribfv, uint_type, enum_type, float_type *);
		DEFINE_API(void, get_vertex_attribiv, uint_type, enum_type, int_type *);
		DEFINE_API(boolean_type, is_program, uint_type);
		DEFINE_API(boolean_type, is_shader, uint_type);
		DEFINE_API(void, link_program, uint_type);
		DEFINE_API(void, shader_source, uint_type, sizei_type, char_type const* const*, int_type const*);
		DEFINE_API(void, stencil_func_separate, enum_type, enum_type, int_type, uint_type);
		DEFINE_API(void, stencil_mask_separate, enum_type, uint_type);
		DEFINE_API(void, stencil_op_separate, enum_type, enum_type, enum_type, enum_type);
		DEFINE_API(void, uniform1f, int_type, float_type);
		DEFINE_API(void, uniform1fv, int_type, sizei_type, float_type const*);
		DEFINE_API(void, uniform1i, int_type, int_type);
		DEFINE_API(void, uniform1iv, int_type, sizei_type, int_type const*);
		DEFINE_API(void, uniform2f, int_type, float_type, float_type);
		DEFINE_API(void, uniform2fv, int_type, sizei_type, float_type const*);
		DEFINE_API(void, uniform2i, int_type, int_type, int_type);
		DEFINE_API(void, uniform2iv, int_type, sizei_type, int_type const*);
		DEFINE_API(void, uniform3f, int_type, float_type, float_type, float_type);
		DEFINE_API(void, uniform3fv, int_type, sizei_type, float_type const*);
		DEFINE_API(void, uniform3i, int_type, int_type, int_type, int_type);
		DEFINE_API(void, uniform3iv, int_type, sizei_type, int_type const*);
		DEFINE_API(void, uniform4f, int_type, float_type, float_type, float_type, float_type);
		DEFINE_API(void, uniform4fv, int_type, sizei_type, float_type const*);
		DEFINE_API(void, uniform4i, int_type, int_type, int_type, int_type, int_type);
		DEFINE_API(void, uniform4iv, int_type, sizei_type, int_type const*);
		DEFINE_API(void, uniform_matrix2fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix3fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix4fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, use_program, uint_type);
		DEFINE_API(void, validate_program, uint_type);
		DEFINE_API(void, vertex_attrib1d, uint_type, double_type);
		DEFINE_API(void, vertex_attrib1dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib1f, uint_type, float_type);
		DEFINE_API(void, vertex_attrib1fv, uint_type, float_type const*);
		DEFINE_API(void, vertex_attrib1s, uint_type, short_type);
		DEFINE_API(void, vertex_attrib1sv, uint_type, short_type const*);
		DEFINE_API(void, vertex_attrib2d, uint_type, double_type, double_type);
		DEFINE_API(void, vertex_attrib2dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib2f, uint_type, float_type, float_type);
		DEFINE_API(void, vertex_attrib2fv, uint_type, float_type const*);
		DEFINE_API(void, vertex_attrib2s, uint_type, short_type, short_type);
		DEFINE_API(void, vertex_attrib2sv, uint_type, short_type const*);
		DEFINE_API(void, vertex_attrib3d, uint_type, double_type, double_type, double_type);
		DEFINE_API(void, vertex_attrib3dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib3f, uint_type, float_type, float_type, float_type);
		DEFINE_API(void, vertex_attrib3fv, uint_type, float_type const*);
		DEFINE_API(void, vertex_attrib3s, uint_type, short_type, short_type, short_type);
		DEFINE_API(void, vertex_attrib3sv, uint_type, short_type const*);
		DEFINE_API(void, vertex_attrib4_nbv, uint_type, byte_type const*);
		DEFINE_API(void, vertex_attrib4_niv, uint_type, int_type const*);
		DEFINE_API(void, vertex_attrib4_nsv, uint_type, short_type const*);
		DEFINE_API(void, vertex_attrib4_nub, uint_type, ubyte_type, ubyte_type, ubyte_type, ubyte_type);
		DEFINE_API(void, vertex_attrib4_nubv, uint_type, ubyte_type const*);
		DEFINE_API(void, vertex_attrib4_nuiv, uint_type, uint_type const*);
		DEFINE_API(void, vertex_attrib4_nusv, uint_type, ushort_type const*);
		DEFINE_API(void, vertex_attrib4bv, uint_type, byte_type const*);
		DEFINE_API(void, vertex_attrib4d, uint_type, double_type, double_type, double_type, double_type);
		DEFINE_API(void, vertex_attrib4dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib4f, uint_type, float_type, float_type, float_type, float_type);
		DEFINE_API(void, vertex_attrib4fv, uint_type, float_type const*);
		DEFINE_API(void, vertex_attrib4iv, uint_type, int_type const*);
		DEFINE_API(void, vertex_attrib4s, uint_type, short_type, short_type, short_type, short_type);
		DEFINE_API(void, vertex_attrib4sv, uint_type, short_type const*);
		DEFINE_API(void, vertex_attrib4ubv, uint_type, ubyte_type const*);
		DEFINE_API(void, vertex_attrib4uiv, uint_type, uint_type const*);
		DEFINE_API(void, vertex_attrib4usv, uint_type, ushort_type const*);
		DEFINE_API(void, vertex_attrib_pointer, uint_type, int_type, enum_type, boolean_type, sizei_type, void const*);

		DEFINE_API(void, uniform_matrix2x3fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix2x4fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix3x2fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix3x4fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix4x2fv, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, uniform_matrix4x3fv, int_type, sizei_type, boolean_type, float_type const*);

		DEFINE_API(void, begin_conditional_render, uint_type, enum_type);
		DEFINE_API(void, begin_transform_feedback, enum_type);
		DEFINE_API(void, bind_buffer_base, enum_type, uint_type, uint_type);
		DEFINE_API(void, bind_buffer_range, enum_type, uint_type, uint_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, bind_frag_data_location, uint_type, uint_type, char_type const*);
		DEFINE_API(void, bind_framebuffer, enum_type, uint_type);
		DEFINE_API(void, bind_renderbuffer, enum_type, uint_type);
		DEFINE_API(void, bind_vertex_array, uint_type);
		DEFINE_API(void, blit_framebuffer, int_type, int_type, int_type, int_type, int_type, int_type, int_type, int_type, bitfield_type, enum_type);
		DEFINE_API(enum_type, check_framebuffer_status, enum_type);
		DEFINE_API(void, clamp_color, enum_type, enum_type);
		DEFINE_API(void, clear_bufferfi, enum_type, int_type, float_type, int_type);
		DEFINE_API(void, clear_bufferfv, enum_type, int_type, float_type const*);
		DEFINE_API(void, clear_bufferiv, enum_type, int_type, int_type const*);
		DEFINE_API(void, clear_bufferuiv, enum_type, int_type, uint_type const*);
		DEFINE_API(void, color_maski, uint_type, boolean_type, boolean_type, boolean_type, boolean_type);
		DEFINE_API(void, delete_framebuffers, sizei_type, uint_type const*);
		DEFINE_API(void, delete_renderbuffers, sizei_type, uint_type const*);
		DEFINE_API(void, delete_vertex_arrays, sizei_type, uint_type const*);
		DEFINE_API(void, disablei, enum_type, uint_type);
		DEFINE_API(void, enablei, enum_type, uint_type);
		DEFINE_API(void, end_conditional_render, void);
		DEFINE_API(void, end_transform_feedback, void);
		DEFINE_API(void, flush_mapped_buffer_range, enum_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, framebuffer_renderbuffer, enum_type, enum_type, enum_type, uint_type);
		DEFINE_API(void, framebuffer_texture1d, enum_type, enum_type, enum_type, uint_type, int_type);
		DEFINE_API(void, framebuffer_texture2d, enum_type, enum_type, enum_type, uint_type, int_type);
		DEFINE_API(void, framebuffer_texture3d, enum_type, enum_type, enum_type, uint_type, int_type, int_type);
		DEFINE_API(void, framebuffer_texture_layer, enum_type, enum_type, uint_type, int_type, int_type);
		DEFINE_API(void, gen_framebuffers, sizei_type, uint_type *);
		DEFINE_API(void, gen_renderbuffers, sizei_type, uint_type *);
		DEFINE_API(void, gen_vertex_arrays, sizei_type, uint_type *);
		DEFINE_API(void, generate_mipmap, enum_type);
		DEFINE_API(void, get_booleani_v, enum_type, uint_type, boolean_type *);
		DEFINE_API(int_type, get_frag_data_location, uint_type, char_type const*);
		DEFINE_API(void, get_framebuffer_attachment_parameteriv, enum_type, enum_type, enum_type, int_type *);
		DEFINE_API(void, get_integeri_v, enum_type, uint_type, int_type *);
		DEFINE_API(void, get_renderbuffer_parameteriv, enum_type, enum_type, int_type *);
		DEFINE_API(ubyte_type const*, get_stringi, enum_type, uint_type);
		DEFINE_API(void, get_tex_parameter_iiv, enum_type, enum_type, int_type *);
		DEFINE_API(void, get_tex_parameter_iuiv, enum_type, enum_type, uint_type *);
		DEFINE_API(void, get_transform_feedback_varying, uint_type, uint_type, sizei_type, sizei_type *, sizei_type *, enum_type *, char_type *);
		DEFINE_API(void, get_uniformuiv, uint_type, int_type, uint_type *);
		DEFINE_API(void, get_vertex_attrib_iiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_vertex_attrib_iuiv, uint_type, enum_type, uint_type *);
		DEFINE_API(boolean_type, is_enabledi, enum_type, uint_type);
		DEFINE_API(boolean_type, is_framebuffer, uint_type);
		DEFINE_API(boolean_type, is_renderbuffer, uint_type);
		DEFINE_API(boolean_type, is_vertex_array, uint_type);
		DEFINE_API(void *, map_buffer_range, enum_type, intptr_type, sizeiptr_type, bitfield_type);
		DEFINE_API(void, renderbuffer_storage, enum_type, enum_type, sizei_type, sizei_type);
		DEFINE_API(void, renderbuffer_storage_multisample, enum_type, sizei_type, enum_type, sizei_type, sizei_type);
		DEFINE_API(void, tex_parameter_iiv, enum_type, enum_type, int_type const*);
		DEFINE_API(void, tex_parameter_iuiv, enum_type, enum_type, uint_type const*);
		DEFINE_API(void, transform_feedback_varyings, uint_type, sizei_type, char_type const* const*, enum_type);
		DEFINE_API(void, uniform1ui, int_type, uint_type);
		DEFINE_API(void, uniform1uiv, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, uniform2ui, int_type, uint_type, uint_type);
		DEFINE_API(void, uniform2uiv, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, uniform3ui, int_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, uniform3uiv, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, uniform4ui, int_type, uint_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, uniform4uiv, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_i1i, uint_type, int_type);
		DEFINE_API(void, vertex_attrib_i1iv, uint_type, int_type const*);
		DEFINE_API(void, vertex_attrib_i1ui, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_i1uiv, uint_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_i2i, uint_type, int_type, int_type);
		DEFINE_API(void, vertex_attrib_i2iv, uint_type, int_type const*);
		DEFINE_API(void, vertex_attrib_i2ui, uint_type, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_i2uiv, uint_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_i3i, uint_type, int_type, int_type, int_type);
		DEFINE_API(void, vertex_attrib_i3iv, uint_type, int_type const*);
		DEFINE_API(void, vertex_attrib_i3ui, uint_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_i3uiv, uint_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_i4bv, uint_type, byte_type const*);
		DEFINE_API(void, vertex_attrib_i4i, uint_type, int_type, int_type, int_type, int_type);
		DEFINE_API(void, vertex_attrib_i4iv, uint_type, int_type const*);
		DEFINE_API(void, vertex_attrib_i4sv, uint_type, short_type const*);
		DEFINE_API(void, vertex_attrib_i4ubv, uint_type, ubyte_type const*);
		DEFINE_API(void, vertex_attrib_i4ui, uint_type, uint_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_i4uiv, uint_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_i4usv, uint_type, ushort_type const*);
		DEFINE_API(void, vertex_attrib_i_pointer, uint_type, int_type, enum_type, sizei_type, void const*);

		DEFINE_API(void, copy_buffer_sub_data, enum_type, enum_type, intptr_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, draw_arrays_instanced, enum_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, draw_elements_instanced, enum_type, sizei_type, enum_type, void const*, sizei_type);
		DEFINE_API(void, get_active_uniform_block_name, uint_type, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_active_uniform_blockiv, uint_type, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_active_uniform_name, uint_type, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_active_uniformsiv, uint_type, sizei_type, uint_type const*, enum_type, int_type *);
		DEFINE_API(uint_type, get_uniform_block_index, uint_type, char_type const*);
		DEFINE_API(void, get_uniform_indices, uint_type, sizei_type, char_type const* const*, uint_type *);
		DEFINE_API(void, primitive_restart_index, uint_type);
		DEFINE_API(void, tex_buffer, enum_type, enum_type, uint_type);
		DEFINE_API(void, uniform_block_binding, uint_type, uint_type, uint_type);

		DEFINE_API(enum_type, client_wait_sync, sync_type, bitfield_type, uint64_type);
		DEFINE_API(void, delete_sync, sync_type);
		DEFINE_API(void, draw_elements_base_vertex, enum_type, sizei_type, enum_type, void const*, int_type);
		DEFINE_API(void, draw_elements_instanced_base_vertex, enum_type, sizei_type, enum_type, void const*, sizei_type, int_type);
		DEFINE_API(void, draw_range_elements_base_vertex, enum_type, uint_type, uint_type, sizei_type, enum_type, void const*, int_type);
		DEFINE_API(sync_type, fence_sync, enum_type, bitfield_type);
		DEFINE_API(void, framebuffer_texture, enum_type, enum_type, uint_type, int_type);
		DEFINE_API(void, get_buffer_parameteri64v, enum_type, enum_type, int64_type *);
		DEFINE_API(void, get_integer64i_v, enum_type, uint_type, int64_type *);
		DEFINE_API(void, get_integer64v, enum_type, int64_type *);
		DEFINE_API(void, get_multisamplefv, enum_type, uint_type, float_type *);
		DEFINE_API(void, get_synciv, sync_type, enum_type, sizei_type, sizei_type *, int_type *);
		DEFINE_API(boolean_type, is_sync, sync_type);
		DEFINE_API(void, multi_draw_elements_base_vertex, enum_type, sizei_type const*, enum_type, void const* const*, sizei_type, int_type const*);
		DEFINE_API(void, provoking_vertex, enum_type);
		DEFINE_API(void, sample_maski, uint_type, bitfield_type);
		DEFINE_API(void, tex_image2d_multisample, enum_type, sizei_type, enum_type, sizei_type, sizei_type, boolean_type);
		DEFINE_API(void, tex_image3d_multisample, enum_type, sizei_type, enum_type, sizei_type, sizei_type, sizei_type, boolean_type);
		DEFINE_API(void, wait_sync, sync_type, bitfield_type, uint64_type);

		DEFINE_API(void, bind_frag_data_location_indexed, uint_type, uint_type, uint_type, char_type const*);
		DEFINE_API(void, bind_sampler, uint_type, uint_type);
		DEFINE_API(void, delete_samplers, sizei_type, uint_type const*);
		DEFINE_API(void, gen_samplers, sizei_type, uint_type *);
		DEFINE_API(int_type, get_frag_data_index, uint_type, char_type const*);
		DEFINE_API(void, get_query_objecti64v, uint_type, enum_type, int64_type *);
		DEFINE_API(void, get_query_objectui64v, uint_type, enum_type, uint64_type *);
		DEFINE_API(void, get_sampler_parameter_iiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_sampler_parameter_iuiv, uint_type, enum_type, uint_type *);
		DEFINE_API(void, get_sampler_parameterfv, uint_type, enum_type, float_type *);
		DEFINE_API(void, get_sampler_parameteriv, uint_type, enum_type, int_type *);
		DEFINE_API(boolean_type, is_sampler, uint_type);
		DEFINE_API(void, query_counter, uint_type, enum_type);
		DEFINE_API(void, sampler_parameter_iiv, uint_type, enum_type, int_type const*);
		DEFINE_API(void, sampler_parameter_iuiv, uint_type, enum_type, uint_type const*);
		DEFINE_API(void, sampler_parameterf, uint_type, enum_type, float_type);
		DEFINE_API(void, sampler_parameterfv, uint_type, enum_type, float_type const*);
		DEFINE_API(void, sampler_parameteri, uint_type, enum_type, int_type);
		DEFINE_API(void, sampler_parameteriv, uint_type, enum_type, int_type const*);
		DEFINE_API(void, vertex_attrib_divisor, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_p1ui, uint_type, enum_type, boolean_type, uint_type);
		DEFINE_API(void, vertex_attrib_p1uiv, uint_type, enum_type, boolean_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_p2ui, uint_type, enum_type, boolean_type, uint_type);
		DEFINE_API(void, vertex_attrib_p2uiv, uint_type, enum_type, boolean_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_p3ui, uint_type, enum_type, boolean_type, uint_type);
		DEFINE_API(void, vertex_attrib_p3uiv, uint_type, enum_type, boolean_type, uint_type const*);
		DEFINE_API(void, vertex_attrib_p4ui, uint_type, enum_type, boolean_type, uint_type);
		DEFINE_API(void, vertex_attrib_p4uiv, uint_type, enum_type, boolean_type, uint_type const*);

		DEFINE_API(void, begin_query_indexed, enum_type, uint_type, uint_type);
		DEFINE_API(void, bind_transform_feedback, enum_type, uint_type);
		DEFINE_API(void, blend_equation_separatei, uint_type, enum_type, enum_type);
		DEFINE_API(void, blend_equationi, uint_type, enum_type);
		DEFINE_API(void, blend_func_separatei, uint_type, enum_type, enum_type, enum_type, enum_type);
		DEFINE_API(void, blend_funci, uint_type, enum_type, enum_type);
		DEFINE_API(void, delete_transform_feedbacks, sizei_type, uint_type const*);
		DEFINE_API(void, draw_arrays_indirect, enum_type, void const*);
		DEFINE_API(void, draw_elements_indirect, enum_type, enum_type, void const*);
		DEFINE_API(void, draw_transform_feedback, enum_type, uint_type);
		DEFINE_API(void, draw_transform_feedback_stream, enum_type, uint_type, uint_type);
		DEFINE_API(void, end_query_indexed, enum_type, uint_type);
		DEFINE_API(void, gen_transform_feedbacks, sizei_type, uint_type *);
		DEFINE_API(void, get_active_subroutine_name, uint_type, enum_type, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_active_subroutine_uniform_name, uint_type, enum_type, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_active_subroutine_uniformiv, uint_type, enum_type, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_program_stageiv, uint_type, enum_type, enum_type, int_type *);
		DEFINE_API(void, get_query_indexediv, enum_type, uint_type, enum_type, int_type *);
		DEFINE_API(uint_type, get_subroutine_index, uint_type, enum_type, char_type const*);
		DEFINE_API(int_type, get_subroutine_uniform_location, uint_type, enum_type, char_type const*);
		DEFINE_API(void, get_uniform_subroutineuiv, enum_type, int_type, uint_type *);
		DEFINE_API(void, get_uniformdv, uint_type, int_type, double_type *);
		DEFINE_API(boolean_type, is_transform_feedback, uint_type);
		DEFINE_API(void, min_sample_shading, float_type);
		DEFINE_API(void, patch_parameterfv, enum_type, float_type const*);
		DEFINE_API(void, patch_parameteri, enum_type, int_type);
		DEFINE_API(void, pause_transform_feedback, void);
		DEFINE_API(void, resume_transform_feedback, void);
		DEFINE_API(void, uniform1d, int_type, double_type);
		DEFINE_API(void, uniform1dv, int_type, sizei_type, double_type const*);
		DEFINE_API(void, uniform2d, int_type, double_type, double_type);
		DEFINE_API(void, uniform2dv, int_type, sizei_type, double_type const*);
		DEFINE_API(void, uniform3d, int_type, double_type, double_type, double_type);
		DEFINE_API(void, uniform3dv, int_type, sizei_type, double_type const*);
		DEFINE_API(void, uniform4d, int_type, double_type, double_type, double_type, double_type);
		DEFINE_API(void, uniform4dv, int_type, sizei_type, double_type const*);
		DEFINE_API(void, uniform_matrix2dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix2x3dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix2x4dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix3dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix3x2dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix3x4dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix4dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix4x2dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_matrix4x3dv, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, uniform_subroutinesuiv, enum_type, sizei_type, uint_type const*);

		DEFINE_API(void, active_shader_program, uint_type, uint_type);
		DEFINE_API(void, bind_program_pipeline, uint_type);
		DEFINE_API(void, clear_depthf, float_type);
		DEFINE_API(uint_type, create_shader_programv, enum_type, sizei_type, char_type const* const*);
		DEFINE_API(void, delete_program_pipelines, sizei_type, uint_type const*);
		DEFINE_API(void, depth_range_arrayv, uint_type, sizei_type, double_type const*);
		DEFINE_API(void, depth_range_indexed, uint_type, double_type, double_type);
		DEFINE_API(void, depth_rangef, float_type, float_type);
		DEFINE_API(void, gen_program_pipelines, sizei_type, uint_type *);
		DEFINE_API(void, get_doublei_v, enum_type, uint_type, double_type *);
		DEFINE_API(void, get_floati_v, enum_type, uint_type, float_type *);
		DEFINE_API(void, get_program_binary, uint_type, sizei_type, sizei_type *, enum_type *, void *);
		DEFINE_API(void, get_program_pipeline_info_log, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_program_pipelineiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_shader_precision_format, enum_type, enum_type, int_type *, int_type *);
		DEFINE_API(void, get_vertex_attrib_ldv, uint_type, enum_type, double_type *);
		DEFINE_API(boolean_type, is_program_pipeline, uint_type);
		DEFINE_API(void, program_binary, uint_type, enum_type, void const*, sizei_type);
		DEFINE_API(void, program_parameteri, uint_type, enum_type, int_type);
		DEFINE_API(void, program_uniform1d, uint_type, int_type, double_type);
		DEFINE_API(void, program_uniform1dv, uint_type, int_type, sizei_type, double_type const*);
		DEFINE_API(void, program_uniform1f, uint_type, int_type, float_type);
		DEFINE_API(void, program_uniform1fv, uint_type, int_type, sizei_type, float_type const*);
		DEFINE_API(void, program_uniform1i, uint_type, int_type, int_type);
		DEFINE_API(void, program_uniform1iv, uint_type, int_type, sizei_type, int_type const*);
		DEFINE_API(void, program_uniform1ui, uint_type, int_type, uint_type);
		DEFINE_API(void, program_uniform1uiv, uint_type, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, program_uniform2d, uint_type, int_type, double_type, double_type);
		DEFINE_API(void, program_uniform2dv, uint_type, int_type, sizei_type, double_type const*);
		DEFINE_API(void, program_uniform2f, uint_type, int_type, float_type, float_type);
		DEFINE_API(void, program_uniform2fv, uint_type, int_type, sizei_type, float_type const*);
		DEFINE_API(void, program_uniform2i, uint_type, int_type, int_type, int_type);
		DEFINE_API(void, program_uniform2iv, uint_type, int_type, sizei_type, int_type const*);
		DEFINE_API(void, program_uniform2ui, uint_type, int_type, uint_type, uint_type);
		DEFINE_API(void, program_uniform2uiv, uint_type, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, program_uniform3d, uint_type, int_type, double_type, double_type, double_type);
		DEFINE_API(void, program_uniform3dv, uint_type, int_type, sizei_type, double_type const*);
		DEFINE_API(void, program_uniform3f, uint_type, int_type, float_type, float_type, float_type);
		DEFINE_API(void, program_uniform3fv, uint_type, int_type, sizei_type, float_type const*);
		DEFINE_API(void, program_uniform3i, uint_type, int_type, int_type, int_type, int_type);
		DEFINE_API(void, program_uniform3iv, uint_type, int_type, sizei_type, int_type const*);
		DEFINE_API(void, program_uniform3ui, uint_type, int_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, program_uniform3uiv, uint_type, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, program_uniform4d, uint_type, int_type, double_type, double_type, double_type, double_type);
		DEFINE_API(void, program_uniform4dv, uint_type, int_type, sizei_type, double_type const*);
		DEFINE_API(void, program_uniform4f, uint_type, int_type, float_type, float_type, float_type, float_type);
		DEFINE_API(void, program_uniform4fv, uint_type, int_type, sizei_type, float_type const*);
		DEFINE_API(void, program_uniform4i, uint_type, int_type, int_type, int_type, int_type, int_type);
		DEFINE_API(void, program_uniform4iv, uint_type, int_type, sizei_type, int_type const*);
		DEFINE_API(void, program_uniform4ui, uint_type, int_type, uint_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, program_uniform4uiv, uint_type, int_type, sizei_type, uint_type const*);
		DEFINE_API(void, program_uniform_matrix2dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix2fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix2x3dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix2x3fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix2x4dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix2x4fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix3dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix3fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix3x2dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix3x2fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix3x4dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix3x4fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix4dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix4fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix4x2dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix4x2fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, program_uniform_matrix4x3dv, uint_type, int_type, sizei_type, boolean_type, double_type const*);
		DEFINE_API(void, program_uniform_matrix4x3fv, uint_type, int_type, sizei_type, boolean_type, float_type const*);
		DEFINE_API(void, release_shader_compiler, void);
		DEFINE_API(void, scissor_arrayv, uint_type, sizei_type, int_type const*);
		DEFINE_API(void, scissor_indexed, uint_type, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, scissor_indexedv, uint_type, int_type const*);
		DEFINE_API(void, shader_binary, sizei_type, uint_type const*, enum_type, void const*, sizei_type);
		DEFINE_API(void, use_program_stages, uint_type, bitfield_type, uint_type);
		DEFINE_API(void, validate_program_pipeline, uint_type);
		DEFINE_API(void, vertex_attrib_l1d, uint_type, double_type);
		DEFINE_API(void, vertex_attrib_l1dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib_l2d, uint_type, double_type, double_type);
		DEFINE_API(void, vertex_attrib_l2dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib_l3d, uint_type, double_type, double_type, double_type);
		DEFINE_API(void, vertex_attrib_l3dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib_l4d, uint_type, double_type, double_type, double_type, double_type);
		DEFINE_API(void, vertex_attrib_l4dv, uint_type, double_type const*);
		DEFINE_API(void, vertex_attrib_l_pointer, uint_type, int_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, viewport_arrayv, uint_type, sizei_type, float_type const*);
		DEFINE_API(void, viewport_indexedf, uint_type, float_type, float_type, float_type, float_type);
		DEFINE_API(void, viewport_indexedfv, uint_type, float_type const*);

		DEFINE_API(void, bind_image_texture, uint_type, uint_type, int_type, boolean_type, int_type, enum_type, enum_type);
		DEFINE_API(void, draw_arrays_instanced_base_instance, enum_type, int_type, sizei_type, sizei_type, uint_type);
		DEFINE_API(void, draw_elements_instanced_base_instance, enum_type, sizei_type, enum_type, void const*, sizei_type, uint_type);
		DEFINE_API(void, draw_elements_instanced_base_vertex_base_instance, enum_type, sizei_type, enum_type, void const*, sizei_type, int_type, uint_type);
		DEFINE_API(void, draw_transform_feedback_instanced, enum_type, uint_type, sizei_type);
		DEFINE_API(void, draw_transform_feedback_stream_instanced, enum_type, uint_type, uint_type, sizei_type);
		DEFINE_API(void, get_active_atomic_counter_bufferiv, uint_type, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_internalformativ, enum_type, enum_type, enum_type, sizei_type, int_type *);
		DEFINE_API(void, memory_barrier, bitfield_type);
		DEFINE_API(void, tex_storage1d, enum_type, sizei_type, enum_type, sizei_type);
		DEFINE_API(void, tex_storage2d, enum_type, sizei_type, enum_type, sizei_type, sizei_type);
		DEFINE_API(void, tex_storage3d, enum_type, sizei_type, enum_type, sizei_type, sizei_type, sizei_type);

		DEFINE_API(void, bind_vertex_buffer, uint_type, uint_type, intptr_type, sizei_type);
		DEFINE_API(void, clear_buffer_data, enum_type, enum_type, enum_type, enum_type, void const*);
		DEFINE_API(void, clear_buffer_sub_data, enum_type, enum_type, intptr_type, sizeiptr_type, enum_type, enum_type, void const*);
		DEFINE_API(void, copy_image_sub_data, uint_type, enum_type, int_type, int_type, int_type, int_type, uint_type, enum_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type);
		DEFINE_API(void, debug_message_callback, debug_proc_type, void const*);
		DEFINE_API(void, debug_message_control, enum_type, enum_type, enum_type, sizei_type, uint_type const*, boolean_type);
		DEFINE_API(void, debug_message_insert, enum_type, enum_type, uint_type, enum_type, sizei_type, char_type const*);
		DEFINE_API(void, dispatch_compute, uint_type, uint_type, uint_type);
		DEFINE_API(void, dispatch_compute_indirect, intptr_type);
		DEFINE_API(void, framebuffer_parameteri, enum_type, enum_type, int_type);
		DEFINE_API(uint_type, get_debug_message_log, uint_type, sizei_type, enum_type *, enum_type *, uint_type *, enum_type *, sizei_type *, char_type *);
		DEFINE_API(void, get_framebuffer_parameteriv, enum_type, enum_type, int_type *);
		DEFINE_API(void, get_internalformati64v, enum_type, enum_type, enum_type, sizei_type, int64_type *);
		DEFINE_API(void, get_object_label, enum_type, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_object_ptr_label, void const*, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_program_interfaceiv, uint_type, enum_type, enum_type, int_type *);
		DEFINE_API(uint_type, get_program_resource_index, uint_type, enum_type, char_type const*);
		DEFINE_API(int_type, get_program_resource_location, uint_type, enum_type, char_type const*);
		DEFINE_API(int_type, get_program_resource_location_index, uint_type, enum_type, char_type const*);
		DEFINE_API(void, get_program_resource_name, uint_type, enum_type, uint_type, sizei_type, sizei_type *, char_type *);
		DEFINE_API(void, get_program_resourceiv, uint_type, enum_type, uint_type, sizei_type, enum_type const*, sizei_type, sizei_type *, int_type *);
		DEFINE_API(void, invalidate_buffer_data, uint_type);
		DEFINE_API(void, invalidate_buffer_sub_data, uint_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, invalidate_framebuffer, enum_type, sizei_type, enum_type const*);
		DEFINE_API(void, invalidate_sub_framebuffer, enum_type, sizei_type, enum_type const*, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, invalidate_tex_image, uint_type, int_type);
		DEFINE_API(void, invalidate_tex_sub_image, uint_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type);
		DEFINE_API(void, multi_draw_arrays_indirect, enum_type, void const*, sizei_type, sizei_type);
		DEFINE_API(void, multi_draw_elements_indirect, enum_type, enum_type, void const*, sizei_type, sizei_type);
		DEFINE_API(void, object_label, enum_type, uint_type, sizei_type, char_type const*);
		DEFINE_API(void, object_ptr_label, void const*, sizei_type, char_type const*);
		DEFINE_API(void, pop_debug_group, void);
		DEFINE_API(void, push_debug_group, enum_type, uint_type, sizei_type, char_type const*);
		DEFINE_API(void, shader_storage_block_binding, uint_type, uint_type, uint_type);
		DEFINE_API(void, tex_buffer_range, enum_type, enum_type, uint_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, tex_storage2d_multisample, enum_type, sizei_type, enum_type, sizei_type, sizei_type, boolean_type);
		DEFINE_API(void, tex_storage3d_multisample, enum_type, sizei_type, enum_type, sizei_type, sizei_type, sizei_type, boolean_type);
		DEFINE_API(void, texture_view, uint_type, enum_type, uint_type, enum_type, uint_type, uint_type, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_binding, uint_type, uint_type);
		DEFINE_API(void, vertex_attrib_format, uint_type, int_type, enum_type, boolean_type, uint_type);
		DEFINE_API(void, vertex_attrib_i_format, uint_type, int_type, enum_type, uint_type);
		DEFINE_API(void, vertex_attrib_l_format, uint_type, int_type, enum_type, uint_type);
		DEFINE_API(void, vertex_binding_divisor, uint_type, uint_type);

		DEFINE_API(void, bind_buffers_base, enum_type, uint_type, sizei_type, uint_type const*);
		DEFINE_API(void, bind_buffers_range, enum_type, uint_type, sizei_type, uint_type const*, intptr_type const*, sizeiptr_type const*);
		DEFINE_API(void, bind_image_textures, uint_type, sizei_type, uint_type const*);
		DEFINE_API(void, bind_samplers, uint_type, sizei_type, uint_type const*);
		DEFINE_API(void, bind_textures, uint_type, sizei_type, uint_type const*);
		DEFINE_API(void, bind_vertex_buffers, uint_type, sizei_type, uint_type const*, intptr_type const*, sizei_type const*);
		DEFINE_API(void, buffer_storage, enum_type, sizeiptr_type, void const*, bitfield_type);
		DEFINE_API(void, clear_tex_image, uint_type, int_type, enum_type, enum_type, void const*);
		DEFINE_API(void, clear_tex_sub_image, uint_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, enum_type, enum_type, void const*);

		DEFINE_API(void, bind_texture_unit, uint_type, uint_type);
		DEFINE_API(void, blit_named_framebuffer, uint_type, uint_type, int_type, int_type, int_type, int_type, int_type, int_type, int_type, int_type, bitfield_type, enum_type);
		DEFINE_API(enum_type, check_named_framebuffer_status, uint_type, enum_type);
		DEFINE_API(void, clear_named_buffer_data, uint_type, enum_type, enum_type, enum_type, void const*);
		DEFINE_API(void, clear_named_buffer_sub_data, uint_type, enum_type, intptr_type, sizeiptr_type, enum_type, enum_type, void const*);
		DEFINE_API(void, clear_named_framebufferfi, uint_type, enum_type, int_type, const float_type, int_type);
		DEFINE_API(void, clear_named_framebufferfv, uint_type, enum_type, int_type, float_type const*);
		DEFINE_API(void, clear_named_framebufferiv, uint_type, enum_type, int_type, int_type const*);
		DEFINE_API(void, clear_named_framebufferuiv, uint_type, enum_type, int_type, uint_type const*);
		DEFINE_API(void, clip_control, enum_type, enum_type);
		DEFINE_API(void, compressed_texture_sub_image1d, uint_type, int_type, int_type, sizei_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, compressed_texture_sub_image2d, uint_type, int_type, int_type, int_type, sizei_type, sizei_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, compressed_texture_sub_image3d, uint_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, enum_type, sizei_type, void const*);
		DEFINE_API(void, copy_named_buffer_sub_data, uint_type, uint_type, intptr_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, copy_texture_sub_image1d, uint_type, int_type, int_type, int_type, int_type, sizei_type);
		DEFINE_API(void, copy_texture_sub_image2d, uint_type, int_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, copy_texture_sub_image3d, uint_type, int_type, int_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void, create_buffers, sizei_type, uint_type *);
		DEFINE_API(void, create_framebuffers, sizei_type, uint_type *);
		DEFINE_API(void, create_program_pipelines, sizei_type, uint_type *);
		DEFINE_API(void, create_queries, enum_type, sizei_type, uint_type *);
		DEFINE_API(void, create_renderbuffers, sizei_type, uint_type *);
		DEFINE_API(void, create_samplers, sizei_type, uint_type *);
		DEFINE_API(void, create_textures, enum_type, sizei_type, uint_type *);
		DEFINE_API(void, create_transform_feedbacks, sizei_type, uint_type *);
		DEFINE_API(void, create_vertex_arrays, sizei_type, uint_type *);
		DEFINE_API(void, disable_vertex_array_attrib, uint_type, uint_type);
		DEFINE_API(void, enable_vertex_array_attrib, uint_type, uint_type);
		DEFINE_API(void, flush_mapped_named_buffer_range, uint_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, generate_texture_mipmap, uint_type);
		DEFINE_API(void, get_compressed_texture_image, uint_type, int_type, sizei_type, void *);
		DEFINE_API(void, get_compressed_texture_sub_image, uint_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, sizei_type, void *);
		DEFINE_API(enum_type, get_graphics_reset_status, void);
		DEFINE_API(void, get_named_buffer_parameteri64v, uint_type, enum_type, int64_type *);
		DEFINE_API(void, get_named_buffer_parameteriv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_named_buffer_pointerv, uint_type, enum_type, void **);
		DEFINE_API(void, get_named_buffer_sub_data, uint_type, intptr_type, sizeiptr_type, void *);
		DEFINE_API(void, get_named_framebuffer_attachment_parameteriv, uint_type, enum_type, enum_type, int_type *);
		DEFINE_API(void, get_named_framebuffer_parameteriv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_named_renderbuffer_parameteriv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_query_buffer_objecti64v, uint_type, uint_type, enum_type, intptr_type);
		DEFINE_API(void, get_query_buffer_objectiv, uint_type, uint_type, enum_type, intptr_type);
		DEFINE_API(void, get_query_buffer_objectui64v, uint_type, uint_type, enum_type, intptr_type);
		DEFINE_API(void, get_query_buffer_objectuiv, uint_type, uint_type, enum_type, intptr_type);
		DEFINE_API(void, get_texture_image, uint_type, int_type, enum_type, enum_type, sizei_type, void *);
		DEFINE_API(void, get_texture_level_parameterfv, uint_type, int_type, enum_type, float_type *);
		DEFINE_API(void, get_texture_level_parameteriv, uint_type, int_type, enum_type, int_type *);
		DEFINE_API(void, get_texture_parameter_iiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_texture_parameter_iuiv, uint_type, enum_type, uint_type *);
		DEFINE_API(void, get_texture_parameterfv, uint_type, enum_type, float_type *);
		DEFINE_API(void, get_texture_parameteriv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_texture_sub_image, uint_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, enum_type, enum_type, sizei_type, void *);
		DEFINE_API(void, get_transform_feedbacki64_v, uint_type, enum_type, uint_type, int64_type *);
		DEFINE_API(void, get_transform_feedbacki_v, uint_type, enum_type, uint_type, int_type *);
		DEFINE_API(void, get_transform_feedbackiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_vertex_array_indexed64iv, uint_type, uint_type, enum_type, int64_type *);
		DEFINE_API(void, get_vertex_array_indexediv, uint_type, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_vertex_arrayiv, uint_type, enum_type, int_type *);
		DEFINE_API(void, get_n_compressed_tex_image, enum_type, int_type, sizei_type, void *);
		DEFINE_API(void, get_n_tex_image, enum_type, int_type, enum_type, enum_type, sizei_type, void *);
		DEFINE_API(void, get_n_uniformdv, uint_type, int_type, sizei_type, double_type *);
		DEFINE_API(void, get_n_uniformfv, uint_type, int_type, sizei_type, float_type *);
		DEFINE_API(void, get_n_uniformiv, uint_type, int_type, sizei_type, int_type *);
		DEFINE_API(void, get_n_uniformuiv, uint_type, int_type, sizei_type, uint_type *);
		DEFINE_API(void, invalidate_named_framebuffer_data, uint_type, sizei_type, enum_type const*);
		DEFINE_API(void, invalidate_named_framebuffer_sub_data, uint_type, sizei_type, enum_type const*, int_type, int_type, sizei_type, sizei_type);
		DEFINE_API(void *, map_named_buffer, uint_type, enum_type);
		DEFINE_API(void *, map_named_buffer_range, uint_type, intptr_type, sizeiptr_type, bitfield_type);
		DEFINE_API(void, memory_barrier_by_region, bitfield_type);
		DEFINE_API(void, named_buffer_data, uint_type, sizeiptr_type, void const*, enum_type);
		DEFINE_API(void, named_buffer_storage, uint_type, sizeiptr_type, void const*, bitfield_type);
		DEFINE_API(void, named_buffer_sub_data, uint_type, intptr_type, sizeiptr_type, void const*);
		DEFINE_API(void, named_framebuffer_draw_buffer, uint_type, enum_type);
		DEFINE_API(void, named_framebuffer_draw_buffers, uint_type, sizei_type, enum_type const*);
		DEFINE_API(void, named_framebuffer_parameteri, uint_type, enum_type, int_type);
		DEFINE_API(void, named_framebuffer_read_buffer, uint_type, enum_type);
		DEFINE_API(void, named_framebuffer_renderbuffer, uint_type, enum_type, enum_type, uint_type);
		DEFINE_API(void, named_framebuffer_texture, uint_type, enum_type, uint_type, int_type);
		DEFINE_API(void, named_framebuffer_texture_layer, uint_type, enum_type, uint_type, int_type, int_type);
		DEFINE_API(void, named_renderbuffer_storage, uint_type, enum_type, sizei_type, sizei_type);
		DEFINE_API(void, named_renderbuffer_storage_multisample, uint_type, sizei_type, enum_type, sizei_type, sizei_type);
		DEFINE_API(void, read_n_pixels, int_type, int_type, sizei_type, sizei_type, enum_type, enum_type, sizei_type, void *);
		DEFINE_API(void, texture_barrier, void);
		DEFINE_API(void, texture_buffer, uint_type, enum_type, uint_type);
		DEFINE_API(void, texture_buffer_range, uint_type, enum_type, uint_type, intptr_type, sizeiptr_type);
		DEFINE_API(void, texture_parameter_iiv, uint_type, enum_type, int_type const*);
		DEFINE_API(void, texture_parameter_iuiv, uint_type, enum_type, uint_type const*);
		DEFINE_API(void, texture_parameterf, uint_type, enum_type, float_type);
		DEFINE_API(void, texture_parameterfv, uint_type, enum_type, float_type const*);
		DEFINE_API(void, texture_parameteri, uint_type, enum_type, int_type);
		DEFINE_API(void, texture_parameteriv, uint_type, enum_type, int_type const*);
		DEFINE_API(void, texture_storage1d, uint_type, sizei_type, enum_type, sizei_type);
		DEFINE_API(void, texture_storage2d, uint_type, sizei_type, enum_type, sizei_type, sizei_type);
		DEFINE_API(void, texture_storage2d_multisample, uint_type, sizei_type, enum_type, sizei_type, sizei_type, boolean_type);
		DEFINE_API(void, texture_storage3d, uint_type, sizei_type, enum_type, sizei_type, sizei_type, sizei_type);
		DEFINE_API(void, texture_storage3d_multisample, uint_type, sizei_type, enum_type, sizei_type, sizei_type, sizei_type, boolean_type);
		DEFINE_API(void, texture_sub_image1d, uint_type, int_type, int_type, sizei_type, enum_type, enum_type, void const*);
		DEFINE_API(void, texture_sub_image2d, uint_type, int_type, int_type, int_type, sizei_type, sizei_type, enum_type, enum_type, void const*);
		DEFINE_API(void, texture_sub_image3d, uint_type, int_type, int_type, int_type, int_type, sizei_type, sizei_type, sizei_type, enum_type, enum_type, void const*);
		DEFINE_API(void, transform_feedback_buffer_base, uint_type, uint_type, uint_type);
		DEFINE_API(void, transform_feedback_buffer_range, uint_type, uint_type, uint_type, intptr_type, sizeiptr_type);
		DEFINE_API(boolean_type, unmap_named_buffer, uint_type);
		DEFINE_API(void, vertex_array_attrib_binding, uint_type, uint_type, uint_type);
		DEFINE_API(void, vertex_array_attrib_format, uint_type, uint_type, int_type, enum_type, boolean_type, uint_type);
		DEFINE_API(void, vertex_array_attrib_i_format, uint_type, uint_type, int_type, enum_type, uint_type);
		DEFINE_API(void, vertex_array_attrib_l_format, uint_type, uint_type, int_type, enum_type, uint_type);
		DEFINE_API(void, vertex_array_binding_divisor, uint_type, uint_type, uint_type);
		DEFINE_API(void, vertex_array_element_buffer, uint_type, uint_type);
		DEFINE_API(void, vertex_array_vertex_buffer, uint_type, uint_type, uint_type, intptr_type, sizei_type);
		DEFINE_API(void, vertex_array_vertex_buffers, uint_type, uint_type, sizei_type, uint_type const*, intptr_type const*, sizei_type const*);

		namespace
		{
			#define LOAD_PROC(VAR, NAME) do { \
				VAR = reinterpret_cast<VAR##_type*>(IntGetProcAddress(NAME)); \
				if (VAR == nullptr) return false; \
			} while (false)
			bool load_core()
			{
				LOAD_PROC(blend_func, "glBlendFunc");
				LOAD_PROC(clear, "glClear");
				LOAD_PROC(clear_color, "glClearColor");
				LOAD_PROC(clear_depth, "glClearDepth");
				LOAD_PROC(clear_stencil, "glClearStencil");
				LOAD_PROC(color_mask, "glColorMask");
				LOAD_PROC(cull_face, "glCullFace");
				LOAD_PROC(depth_func, "glDepthFunc");
				LOAD_PROC(depth_mask, "glDepthMask");
				LOAD_PROC(depth_range, "glDepthRange");
				LOAD_PROC(disable, "glDisable");
				LOAD_PROC(draw_buffer, "glDrawBuffer");
				LOAD_PROC(enable, "glEnable");
				LOAD_PROC(finish, "glFinish");
				LOAD_PROC(flush, "glFlush");
				LOAD_PROC(front_face, "glFrontFace");
				LOAD_PROC(get_booleanv, "glGetBooleanv");
				LOAD_PROC(get_doublev, "glGetDoublev");
				LOAD_PROC(get_error, "glGetError");
				LOAD_PROC(get_floatv, "glGetFloatv");
				LOAD_PROC(get_integerv, "glGetIntegerv");
				LOAD_PROC(get_string, "glGetString");
				LOAD_PROC(get_tex_image, "glGetTexImage");
				LOAD_PROC(get_tex_level_parameterfv, "glGetTexLevelParameterfv");
				LOAD_PROC(get_tex_level_parameteriv, "glGetTexLevelParameteriv");
				LOAD_PROC(get_tex_parameterfv, "glGetTexParameterfv");
				LOAD_PROC(get_tex_parameteriv, "glGetTexParameteriv");
				LOAD_PROC(hint, "glHint");
				LOAD_PROC(is_enabled, "glIsEnabled");
				LOAD_PROC(line_width, "glLineWidth");
				LOAD_PROC(logic_op, "glLogicOp");
				LOAD_PROC(pixel_storef, "glPixelStoref");
				LOAD_PROC(pixel_storei, "glPixelStorei");
				LOAD_PROC(point_size, "glPointSize");
				LOAD_PROC(polygon_mode, "glPolygonMode");
				LOAD_PROC(read_buffer, "glReadBuffer");
				LOAD_PROC(read_pixels, "glReadPixels");
				LOAD_PROC(scissor, "glScissor");
				LOAD_PROC(stencil_func, "glStencilFunc");
				LOAD_PROC(stencil_mask, "glStencilMask");
				LOAD_PROC(stencil_op, "glStencilOp");
				LOAD_PROC(tex_image1d, "glTexImage1D");
				LOAD_PROC(tex_image2d, "glTexImage2D");
				LOAD_PROC(tex_parameterf, "glTexParameterf");
				LOAD_PROC(tex_parameterfv, "glTexParameterfv");
				LOAD_PROC(tex_parameteri, "glTexParameteri");
				LOAD_PROC(tex_parameteriv, "glTexParameteriv");
				LOAD_PROC(viewport, "glViewport");
				LOAD_PROC(bind_texture, "glBindTexture");
				LOAD_PROC(copy_tex_image1d, "glCopyTexImage1D");
				LOAD_PROC(copy_tex_image2d, "glCopyTexImage2D");
				LOAD_PROC(copy_tex_sub_image1d, "glCopyTexSubImage1D");
				LOAD_PROC(copy_tex_sub_image2d, "glCopyTexSubImage2D");
				LOAD_PROC(delete_textures, "glDeleteTextures");
				LOAD_PROC(draw_arrays, "glDrawArrays");
				LOAD_PROC(draw_elements, "glDrawElements");
				LOAD_PROC(gen_textures, "glGenTextures");
				LOAD_PROC(get_pointerv, "glGetPointerv");
				LOAD_PROC(is_texture, "glIsTexture");
				LOAD_PROC(polygon_offset, "glPolygonOffset");
				LOAD_PROC(tex_sub_image1d, "glTexSubImage1D");
				LOAD_PROC(tex_sub_image2d, "glTexSubImage2D");
				LOAD_PROC(copy_tex_sub_image3d, "glCopyTexSubImage3D");
				LOAD_PROC(draw_range_elements, "glDrawRangeElements");
				LOAD_PROC(tex_image3d, "glTexImage3D");
				LOAD_PROC(tex_sub_image3d, "glTexSubImage3D");
				LOAD_PROC(active_texture, "glActiveTexture");
				LOAD_PROC(compressed_tex_image1d, "glCompressedTexImage1D");
				LOAD_PROC(compressed_tex_image2d, "glCompressedTexImage2D");
				LOAD_PROC(compressed_tex_image3d, "glCompressedTexImage3D");
				LOAD_PROC(compressed_tex_sub_image1d, "glCompressedTexSubImage1D");
				LOAD_PROC(compressed_tex_sub_image2d, "glCompressedTexSubImage2D");
				LOAD_PROC(compressed_tex_sub_image3d, "glCompressedTexSubImage3D");
				LOAD_PROC(get_compressed_tex_image, "glGetCompressedTexImage");
				LOAD_PROC(sample_coverage, "glSampleCoverage");
				LOAD_PROC(blend_color, "glBlendColor");
				LOAD_PROC(blend_equation, "glBlendEquation");
				LOAD_PROC(blend_func_separate, "glBlendFuncSeparate");
				LOAD_PROC(multi_draw_arrays, "glMultiDrawArrays");
				LOAD_PROC(multi_draw_elements, "glMultiDrawElements");
				LOAD_PROC(point_parameterf, "glPointParameterf");
				LOAD_PROC(point_parameterfv, "glPointParameterfv");
				LOAD_PROC(point_parameteri, "glPointParameteri");
				LOAD_PROC(point_parameteriv, "glPointParameteriv");
				LOAD_PROC(begin_query, "glBeginQuery");
				LOAD_PROC(bind_buffer, "glBindBuffer");
				LOAD_PROC(buffer_data, "glBufferData");
				LOAD_PROC(buffer_sub_data, "glBufferSubData");
				LOAD_PROC(delete_buffers, "glDeleteBuffers");
				LOAD_PROC(delete_queries, "glDeleteQueries");
				LOAD_PROC(end_query, "glEndQuery");
				LOAD_PROC(gen_buffers, "glGenBuffers");
				LOAD_PROC(gen_queries, "glGenQueries");
				LOAD_PROC(get_buffer_parameteriv, "glGetBufferParameteriv");
				LOAD_PROC(get_buffer_pointerv, "glGetBufferPointerv");
				LOAD_PROC(get_buffer_sub_data, "glGetBufferSubData");
				LOAD_PROC(get_query_objectiv, "glGetQueryObjectiv");
				LOAD_PROC(get_query_objectuiv, "glGetQueryObjectuiv");
				LOAD_PROC(get_queryiv, "glGetQueryiv");
				LOAD_PROC(is_buffer, "glIsBuffer");
				LOAD_PROC(is_query, "glIsQuery");
				LOAD_PROC(map_buffer, "glMapBuffer");
				LOAD_PROC(unmap_buffer, "glUnmapBuffer");
				LOAD_PROC(attach_shader, "glAttachShader");
				LOAD_PROC(bind_attrib_location, "glBindAttribLocation");
				LOAD_PROC(blend_equation_separate, "glBlendEquationSeparate");
				LOAD_PROC(compile_shader, "glCompileShader");
				LOAD_PROC(create_program, "glCreateProgram");
				LOAD_PROC(create_shader, "glCreateShader");
				LOAD_PROC(delete_program, "glDeleteProgram");
				LOAD_PROC(delete_shader, "glDeleteShader");
				LOAD_PROC(detach_shader, "glDetachShader");
				LOAD_PROC(disable_vertex_attrib_array, "glDisableVertexAttribArray");
				LOAD_PROC(draw_buffers, "glDrawBuffers");
				LOAD_PROC(enable_vertex_attrib_array, "glEnableVertexAttribArray");
				LOAD_PROC(get_active_attrib, "glGetActiveAttrib");
				LOAD_PROC(get_active_uniform, "glGetActiveUniform");
				LOAD_PROC(get_attached_shaders, "glGetAttachedShaders");
				LOAD_PROC(get_attrib_location, "glGetAttribLocation");
				LOAD_PROC(get_program_info_log, "glGetProgramInfoLog");
				LOAD_PROC(get_programiv, "glGetProgramiv");
				LOAD_PROC(get_shader_info_log, "glGetShaderInfoLog");
				LOAD_PROC(get_shader_source, "glGetShaderSource");
				LOAD_PROC(get_shaderiv, "glGetShaderiv");
				LOAD_PROC(get_uniform_location, "glGetUniformLocation");
				LOAD_PROC(get_uniformfv, "glGetUniformfv");
				LOAD_PROC(get_uniformiv, "glGetUniformiv");
				LOAD_PROC(get_vertex_attrib_pointerv, "glGetVertexAttribPointerv");
				LOAD_PROC(get_vertex_attribdv, "glGetVertexAttribdv");
				LOAD_PROC(get_vertex_attribfv, "glGetVertexAttribfv");
				LOAD_PROC(get_vertex_attribiv, "glGetVertexAttribiv");
				LOAD_PROC(is_program, "glIsProgram");
				LOAD_PROC(is_shader, "glIsShader");
				LOAD_PROC(link_program, "glLinkProgram");
				LOAD_PROC(shader_source, "glShaderSource");
				LOAD_PROC(stencil_func_separate, "glStencilFuncSeparate");
				LOAD_PROC(stencil_mask_separate, "glStencilMaskSeparate");
				LOAD_PROC(stencil_op_separate, "glStencilOpSeparate");
				LOAD_PROC(uniform1f, "glUniform1f");
				LOAD_PROC(uniform1fv, "glUniform1fv");
				LOAD_PROC(uniform1i, "glUniform1i");
				LOAD_PROC(uniform1iv, "glUniform1iv");
				LOAD_PROC(uniform2f, "glUniform2f");
				LOAD_PROC(uniform2fv, "glUniform2fv");
				LOAD_PROC(uniform2i, "glUniform2i");
				LOAD_PROC(uniform2iv, "glUniform2iv");
				LOAD_PROC(uniform3f, "glUniform3f");
				LOAD_PROC(uniform3fv, "glUniform3fv");
				LOAD_PROC(uniform3i, "glUniform3i");
				LOAD_PROC(uniform3iv, "glUniform3iv");
				LOAD_PROC(uniform4f, "glUniform4f");
				LOAD_PROC(uniform4fv, "glUniform4fv");
				LOAD_PROC(uniform4i, "glUniform4i");
				LOAD_PROC(uniform4iv, "glUniform4iv");
				LOAD_PROC(uniform_matrix2fv, "glUniformMatrix2fv");
				LOAD_PROC(uniform_matrix3fv, "glUniformMatrix3fv");
				LOAD_PROC(uniform_matrix4fv, "glUniformMatrix4fv");
				LOAD_PROC(use_program, "glUseProgram");
				LOAD_PROC(validate_program, "glValidateProgram");
				LOAD_PROC(vertex_attrib1d, "glVertexAttrib1d");
				LOAD_PROC(vertex_attrib1dv, "glVertexAttrib1dv");
				LOAD_PROC(vertex_attrib1f, "glVertexAttrib1f");
				LOAD_PROC(vertex_attrib1fv, "glVertexAttrib1fv");
				LOAD_PROC(vertex_attrib1s, "glVertexAttrib1s");
				LOAD_PROC(vertex_attrib1sv, "glVertexAttrib1sv");
				LOAD_PROC(vertex_attrib2d, "glVertexAttrib2d");
				LOAD_PROC(vertex_attrib2dv, "glVertexAttrib2dv");
				LOAD_PROC(vertex_attrib2f, "glVertexAttrib2f");
				LOAD_PROC(vertex_attrib2fv, "glVertexAttrib2fv");
				LOAD_PROC(vertex_attrib2s, "glVertexAttrib2s");
				LOAD_PROC(vertex_attrib2sv, "glVertexAttrib2sv");
				LOAD_PROC(vertex_attrib3d, "glVertexAttrib3d");
				LOAD_PROC(vertex_attrib3dv, "glVertexAttrib3dv");
				LOAD_PROC(vertex_attrib3f, "glVertexAttrib3f");
				LOAD_PROC(vertex_attrib3fv, "glVertexAttrib3fv");
				LOAD_PROC(vertex_attrib3s, "glVertexAttrib3s");
				LOAD_PROC(vertex_attrib3sv, "glVertexAttrib3sv");
				LOAD_PROC(vertex_attrib4_nbv, "glVertexAttrib4Nbv");
				LOAD_PROC(vertex_attrib4_niv, "glVertexAttrib4Niv");
				LOAD_PROC(vertex_attrib4_nsv, "glVertexAttrib4Nsv");
				LOAD_PROC(vertex_attrib4_nub, "glVertexAttrib4Nub");
				LOAD_PROC(vertex_attrib4_nubv, "glVertexAttrib4Nubv");
				LOAD_PROC(vertex_attrib4_nuiv, "glVertexAttrib4Nuiv");
				LOAD_PROC(vertex_attrib4_nusv, "glVertexAttrib4Nusv");
				LOAD_PROC(vertex_attrib4bv, "glVertexAttrib4bv");
				LOAD_PROC(vertex_attrib4d, "glVertexAttrib4d");
				LOAD_PROC(vertex_attrib4dv, "glVertexAttrib4dv");
				LOAD_PROC(vertex_attrib4f, "glVertexAttrib4f");
				LOAD_PROC(vertex_attrib4fv, "glVertexAttrib4fv");
				LOAD_PROC(vertex_attrib4iv, "glVertexAttrib4iv");
				LOAD_PROC(vertex_attrib4s, "glVertexAttrib4s");
				LOAD_PROC(vertex_attrib4sv, "glVertexAttrib4sv");
				LOAD_PROC(vertex_attrib4ubv, "glVertexAttrib4ubv");
				LOAD_PROC(vertex_attrib4uiv, "glVertexAttrib4uiv");
				LOAD_PROC(vertex_attrib4usv, "glVertexAttrib4usv");
				LOAD_PROC(vertex_attrib_pointer, "glVertexAttribPointer");
				LOAD_PROC(uniform_matrix2x3fv, "glUniformMatrix2x3fv");
				LOAD_PROC(uniform_matrix2x4fv, "glUniformMatrix2x4fv");
				LOAD_PROC(uniform_matrix3x2fv, "glUniformMatrix3x2fv");
				LOAD_PROC(uniform_matrix3x4fv, "glUniformMatrix3x4fv");
				LOAD_PROC(uniform_matrix4x2fv, "glUniformMatrix4x2fv");
				LOAD_PROC(uniform_matrix4x3fv, "glUniformMatrix4x3fv");
				LOAD_PROC(begin_conditional_render, "glBeginConditionalRender");
				LOAD_PROC(begin_transform_feedback, "glBeginTransformFeedback");
				LOAD_PROC(bind_buffer_base, "glBindBufferBase");
				LOAD_PROC(bind_buffer_range, "glBindBufferRange");
				LOAD_PROC(bind_frag_data_location, "glBindFragDataLocation");
				LOAD_PROC(bind_framebuffer, "glBindFramebuffer");
				LOAD_PROC(bind_renderbuffer, "glBindRenderbuffer");
				LOAD_PROC(bind_vertex_array, "glBindVertexArray");
				LOAD_PROC(blit_framebuffer, "glBlitFramebuffer");
				LOAD_PROC(check_framebuffer_status, "glCheckFramebufferStatus");
				LOAD_PROC(clamp_color, "glClampColor");
				LOAD_PROC(clear_bufferfi, "glClearBufferfi");
				LOAD_PROC(clear_bufferfv, "glClearBufferfv");
				LOAD_PROC(clear_bufferiv, "glClearBufferiv");
				LOAD_PROC(clear_bufferuiv, "glClearBufferuiv");
				LOAD_PROC(color_maski, "glColorMaski");
				LOAD_PROC(delete_framebuffers, "glDeleteFramebuffers");
				LOAD_PROC(delete_renderbuffers, "glDeleteRenderbuffers");
				LOAD_PROC(delete_vertex_arrays, "glDeleteVertexArrays");
				LOAD_PROC(disablei, "glDisablei");
				LOAD_PROC(enablei, "glEnablei");
				LOAD_PROC(end_conditional_render, "glEndConditionalRender");
				LOAD_PROC(end_transform_feedback, "glEndTransformFeedback");
				LOAD_PROC(flush_mapped_buffer_range, "glFlushMappedBufferRange");
				LOAD_PROC(framebuffer_renderbuffer, "glFramebufferRenderbuffer");
				LOAD_PROC(framebuffer_texture1d, "glFramebufferTexture1D");
				LOAD_PROC(framebuffer_texture2d, "glFramebufferTexture2D");
				LOAD_PROC(framebuffer_texture3d, "glFramebufferTexture3D");
				LOAD_PROC(framebuffer_texture_layer, "glFramebufferTextureLayer");
				LOAD_PROC(gen_framebuffers, "glGenFramebuffers");
				LOAD_PROC(gen_renderbuffers, "glGenRenderbuffers");
				LOAD_PROC(gen_vertex_arrays, "glGenVertexArrays");
				LOAD_PROC(generate_mipmap, "glGenerateMipmap");
				LOAD_PROC(get_booleani_v, "glGetBooleani_v");
				LOAD_PROC(get_frag_data_location, "glGetFragDataLocation");
				LOAD_PROC(get_framebuffer_attachment_parameteriv, "glGetFramebufferAttachmentParameteriv");
				LOAD_PROC(get_integeri_v, "glGetIntegeri_v");
				LOAD_PROC(get_renderbuffer_parameteriv, "glGetRenderbufferParameteriv");
				LOAD_PROC(get_stringi, "glGetStringi");
				LOAD_PROC(get_tex_parameter_iiv, "glGetTexParameterIiv");
				LOAD_PROC(get_tex_parameter_iuiv, "glGetTexParameterIuiv");
				LOAD_PROC(get_transform_feedback_varying, "glGetTransformFeedbackVarying");
				LOAD_PROC(get_uniformuiv, "glGetUniformuiv");
				LOAD_PROC(get_vertex_attrib_iiv, "glGetVertexAttribIiv");
				LOAD_PROC(get_vertex_attrib_iuiv, "glGetVertexAttribIuiv");
				LOAD_PROC(is_enabledi, "glIsEnabledi");
				LOAD_PROC(is_framebuffer, "glIsFramebuffer");
				LOAD_PROC(is_renderbuffer, "glIsRenderbuffer");
				LOAD_PROC(is_vertex_array, "glIsVertexArray");
				LOAD_PROC(map_buffer_range, "glMapBufferRange");
				LOAD_PROC(renderbuffer_storage, "glRenderbufferStorage");
				LOAD_PROC(renderbuffer_storage_multisample, "glRenderbufferStorageMultisample");
				LOAD_PROC(tex_parameter_iiv, "glTexParameterIiv");
				LOAD_PROC(tex_parameter_iuiv, "glTexParameterIuiv");
				LOAD_PROC(transform_feedback_varyings, "glTransformFeedbackVaryings");
				LOAD_PROC(uniform1ui, "glUniform1ui");
				LOAD_PROC(uniform1uiv, "glUniform1uiv");
				LOAD_PROC(uniform2ui, "glUniform2ui");
				LOAD_PROC(uniform2uiv, "glUniform2uiv");
				LOAD_PROC(uniform3ui, "glUniform3ui");
				LOAD_PROC(uniform3uiv, "glUniform3uiv");
				LOAD_PROC(uniform4ui, "glUniform4ui");
				LOAD_PROC(uniform4uiv, "glUniform4uiv");
				LOAD_PROC(vertex_attrib_i1i, "glVertexAttribI1i");
				LOAD_PROC(vertex_attrib_i1iv, "glVertexAttribI1iv");
				LOAD_PROC(vertex_attrib_i1ui, "glVertexAttribI1ui");
				LOAD_PROC(vertex_attrib_i1uiv, "glVertexAttribI1uiv");
				LOAD_PROC(vertex_attrib_i2i, "glVertexAttribI2i");
				LOAD_PROC(vertex_attrib_i2iv, "glVertexAttribI2iv");
				LOAD_PROC(vertex_attrib_i2ui, "glVertexAttribI2ui");
				LOAD_PROC(vertex_attrib_i2uiv, "glVertexAttribI2uiv");
				LOAD_PROC(vertex_attrib_i3i, "glVertexAttribI3i");
				LOAD_PROC(vertex_attrib_i3iv, "glVertexAttribI3iv");
				LOAD_PROC(vertex_attrib_i3ui, "glVertexAttribI3ui");
				LOAD_PROC(vertex_attrib_i3uiv, "glVertexAttribI3uiv");
				LOAD_PROC(vertex_attrib_i4bv, "glVertexAttribI4bv");
				LOAD_PROC(vertex_attrib_i4i, "glVertexAttribI4i");
				LOAD_PROC(vertex_attrib_i4iv, "glVertexAttribI4iv");
				LOAD_PROC(vertex_attrib_i4sv, "glVertexAttribI4sv");
				LOAD_PROC(vertex_attrib_i4ubv, "glVertexAttribI4ubv");
				LOAD_PROC(vertex_attrib_i4ui, "glVertexAttribI4ui");
				LOAD_PROC(vertex_attrib_i4uiv, "glVertexAttribI4uiv");
				LOAD_PROC(vertex_attrib_i4usv, "glVertexAttribI4usv");
				LOAD_PROC(vertex_attrib_i_pointer, "glVertexAttribIPointer");
				LOAD_PROC(copy_buffer_sub_data, "glCopyBufferSubData");
				LOAD_PROC(draw_arrays_instanced, "glDrawArraysInstanced");
				LOAD_PROC(draw_elements_instanced, "glDrawElementsInstanced");
				LOAD_PROC(get_active_uniform_block_name, "glGetActiveUniformBlockName");
				LOAD_PROC(get_active_uniform_blockiv, "glGetActiveUniformBlockiv");
				LOAD_PROC(get_active_uniform_name, "glGetActiveUniformName");
				LOAD_PROC(get_active_uniformsiv, "glGetActiveUniformsiv");
				LOAD_PROC(get_uniform_block_index, "glGetUniformBlockIndex");
				LOAD_PROC(get_uniform_indices, "glGetUniformIndices");
				LOAD_PROC(primitive_restart_index, "glPrimitiveRestartIndex");
				LOAD_PROC(tex_buffer, "glTexBuffer");
				LOAD_PROC(uniform_block_binding, "glUniformBlockBinding");
				LOAD_PROC(client_wait_sync, "glClientWaitSync");
				LOAD_PROC(delete_sync, "glDeleteSync");
				LOAD_PROC(draw_elements_base_vertex, "glDrawElementsBaseVertex");
				LOAD_PROC(draw_elements_instanced_base_vertex, "glDrawElementsInstancedBaseVertex");
				LOAD_PROC(draw_range_elements_base_vertex, "glDrawRangeElementsBaseVertex");
				LOAD_PROC(fence_sync, "glFenceSync");
				LOAD_PROC(framebuffer_texture, "glFramebufferTexture");
				LOAD_PROC(get_buffer_parameteri64v, "glGetBufferParameteri64v");
				LOAD_PROC(get_integer64i_v, "glGetInteger64i_v");
				LOAD_PROC(get_integer64v, "glGetInteger64v");
				LOAD_PROC(get_multisamplefv, "glGetMultisamplefv");
				LOAD_PROC(get_synciv, "glGetSynciv");
				LOAD_PROC(is_sync, "glIsSync");
				LOAD_PROC(multi_draw_elements_base_vertex, "glMultiDrawElementsBaseVertex");
				LOAD_PROC(provoking_vertex, "glProvokingVertex");
				LOAD_PROC(sample_maski, "glSampleMaski");
				LOAD_PROC(tex_image2d_multisample, "glTexImage2DMultisample");
				LOAD_PROC(tex_image3d_multisample, "glTexImage3DMultisample");
				LOAD_PROC(wait_sync, "glWaitSync");
				LOAD_PROC(bind_frag_data_location_indexed, "glBindFragDataLocationIndexed");
				LOAD_PROC(bind_sampler, "glBindSampler");
				LOAD_PROC(delete_samplers, "glDeleteSamplers");
				LOAD_PROC(gen_samplers, "glGenSamplers");
				LOAD_PROC(get_frag_data_index, "glGetFragDataIndex");
				LOAD_PROC(get_query_objecti64v, "glGetQueryObjecti64v");
				LOAD_PROC(get_query_objectui64v, "glGetQueryObjectui64v");
				LOAD_PROC(get_sampler_parameter_iiv, "glGetSamplerParameterIiv");
				LOAD_PROC(get_sampler_parameter_iuiv, "glGetSamplerParameterIuiv");
				LOAD_PROC(get_sampler_parameterfv, "glGetSamplerParameterfv");
				LOAD_PROC(get_sampler_parameteriv, "glGetSamplerParameteriv");
				LOAD_PROC(is_sampler, "glIsSampler");
				LOAD_PROC(query_counter, "glQueryCounter");
				LOAD_PROC(sampler_parameter_iiv, "glSamplerParameterIiv");
				LOAD_PROC(sampler_parameter_iuiv, "glSamplerParameterIuiv");
				LOAD_PROC(sampler_parameterf, "glSamplerParameterf");
				LOAD_PROC(sampler_parameterfv, "glSamplerParameterfv");
				LOAD_PROC(sampler_parameteri, "glSamplerParameteri");
				LOAD_PROC(sampler_parameteriv, "glSamplerParameteriv");
				LOAD_PROC(vertex_attrib_divisor, "glVertexAttribDivisor");
				LOAD_PROC(vertex_attrib_p1ui, "glVertexAttribP1ui");
				LOAD_PROC(vertex_attrib_p1uiv, "glVertexAttribP1uiv");
				LOAD_PROC(vertex_attrib_p2ui, "glVertexAttribP2ui");
				LOAD_PROC(vertex_attrib_p2uiv, "glVertexAttribP2uiv");
				LOAD_PROC(vertex_attrib_p3ui, "glVertexAttribP3ui");
				LOAD_PROC(vertex_attrib_p3uiv, "glVertexAttribP3uiv");
				LOAD_PROC(vertex_attrib_p4ui, "glVertexAttribP4ui");
				LOAD_PROC(vertex_attrib_p4uiv, "glVertexAttribP4uiv");
				LOAD_PROC(begin_query_indexed, "glBeginQueryIndexed");
				LOAD_PROC(bind_transform_feedback, "glBindTransformFeedback");
				LOAD_PROC(blend_equation_separatei, "glBlendEquationSeparatei");
				LOAD_PROC(blend_equationi, "glBlendEquationi");
				LOAD_PROC(blend_func_separatei, "glBlendFuncSeparatei");
				LOAD_PROC(blend_funci, "glBlendFunci");
				LOAD_PROC(delete_transform_feedbacks, "glDeleteTransformFeedbacks");
				LOAD_PROC(draw_arrays_indirect, "glDrawArraysIndirect");
				LOAD_PROC(draw_elements_indirect, "glDrawElementsIndirect");
				LOAD_PROC(draw_transform_feedback, "glDrawTransformFeedback");
				LOAD_PROC(draw_transform_feedback_stream, "glDrawTransformFeedbackStream");
				LOAD_PROC(end_query_indexed, "glEndQueryIndexed");
				LOAD_PROC(gen_transform_feedbacks, "glGenTransformFeedbacks");
				LOAD_PROC(get_active_subroutine_name, "glGetActiveSubroutineName");
				LOAD_PROC(get_active_subroutine_uniform_name, "glGetActiveSubroutineUniformName");
				LOAD_PROC(get_active_subroutine_uniformiv, "glGetActiveSubroutineUniformiv");
				LOAD_PROC(get_program_stageiv, "glGetProgramStageiv");
				LOAD_PROC(get_query_indexediv, "glGetQueryIndexediv");
				LOAD_PROC(get_subroutine_index, "glGetSubroutineIndex");
				LOAD_PROC(get_subroutine_uniform_location, "glGetSubroutineUniformLocation");
				LOAD_PROC(get_uniform_subroutineuiv, "glGetUniformSubroutineuiv");
				LOAD_PROC(get_uniformdv, "glGetUniformdv");
				LOAD_PROC(is_transform_feedback, "glIsTransformFeedback");
				LOAD_PROC(min_sample_shading, "glMinSampleShading");
				LOAD_PROC(patch_parameterfv, "glPatchParameterfv");
				LOAD_PROC(patch_parameteri, "glPatchParameteri");
				LOAD_PROC(pause_transform_feedback, "glPauseTransformFeedback");
				LOAD_PROC(resume_transform_feedback, "glResumeTransformFeedback");
				LOAD_PROC(uniform1d, "glUniform1d");
				LOAD_PROC(uniform1dv, "glUniform1dv");
				LOAD_PROC(uniform2d, "glUniform2d");
				LOAD_PROC(uniform2dv, "glUniform2dv");
				LOAD_PROC(uniform3d, "glUniform3d");
				LOAD_PROC(uniform3dv, "glUniform3dv");
				LOAD_PROC(uniform4d, "glUniform4d");
				LOAD_PROC(uniform4dv, "glUniform4dv");
				LOAD_PROC(uniform_matrix2dv, "glUniformMatrix2dv");
				LOAD_PROC(uniform_matrix2x3dv, "glUniformMatrix2x3dv");
				LOAD_PROC(uniform_matrix2x4dv, "glUniformMatrix2x4dv");
				LOAD_PROC(uniform_matrix3dv, "glUniformMatrix3dv");
				LOAD_PROC(uniform_matrix3x2dv, "glUniformMatrix3x2dv");
				LOAD_PROC(uniform_matrix3x4dv, "glUniformMatrix3x4dv");
				LOAD_PROC(uniform_matrix4dv, "glUniformMatrix4dv");
				LOAD_PROC(uniform_matrix4x2dv, "glUniformMatrix4x2dv");
				LOAD_PROC(uniform_matrix4x3dv, "glUniformMatrix4x3dv");
				LOAD_PROC(uniform_subroutinesuiv, "glUniformSubroutinesuiv");
				LOAD_PROC(active_shader_program, "glActiveShaderProgram");
				LOAD_PROC(bind_program_pipeline, "glBindProgramPipeline");
				LOAD_PROC(clear_depthf, "glClearDepthf");
				LOAD_PROC(create_shader_programv, "glCreateShaderProgramv");
				LOAD_PROC(delete_program_pipelines, "glDeleteProgramPipelines");
				LOAD_PROC(depth_range_arrayv, "glDepthRangeArrayv");
				LOAD_PROC(depth_range_indexed, "glDepthRangeIndexed");
				LOAD_PROC(depth_rangef, "glDepthRangef");
				LOAD_PROC(gen_program_pipelines, "glGenProgramPipelines");
				LOAD_PROC(get_doublei_v, "glGetDoublei_v");
				LOAD_PROC(get_floati_v, "glGetFloati_v");
				LOAD_PROC(get_program_binary, "glGetProgramBinary");
				LOAD_PROC(get_program_pipeline_info_log, "glGetProgramPipelineInfoLog");
				LOAD_PROC(get_program_pipelineiv, "glGetProgramPipelineiv");
				LOAD_PROC(get_shader_precision_format, "glGetShaderPrecisionFormat");
				LOAD_PROC(get_vertex_attrib_ldv, "glGetVertexAttribLdv");
				LOAD_PROC(is_program_pipeline, "glIsProgramPipeline");
				LOAD_PROC(program_binary, "glProgramBinary");
				LOAD_PROC(program_parameteri, "glProgramParameteri");
				LOAD_PROC(program_uniform1d, "glProgramUniform1d");
				LOAD_PROC(program_uniform1dv, "glProgramUniform1dv");
				LOAD_PROC(program_uniform1f, "glProgramUniform1f");
				LOAD_PROC(program_uniform1fv, "glProgramUniform1fv");
				LOAD_PROC(program_uniform1i, "glProgramUniform1i");
				LOAD_PROC(program_uniform1iv, "glProgramUniform1iv");
				LOAD_PROC(program_uniform1ui, "glProgramUniform1ui");
				LOAD_PROC(program_uniform1uiv, "glProgramUniform1uiv");
				LOAD_PROC(program_uniform2d, "glProgramUniform2d");
				LOAD_PROC(program_uniform2dv, "glProgramUniform2dv");
				LOAD_PROC(program_uniform2f, "glProgramUniform2f");
				LOAD_PROC(program_uniform2fv, "glProgramUniform2fv");
				LOAD_PROC(program_uniform2i, "glProgramUniform2i");
				LOAD_PROC(program_uniform2iv, "glProgramUniform2iv");
				LOAD_PROC(program_uniform2ui, "glProgramUniform2ui");
				LOAD_PROC(program_uniform2uiv, "glProgramUniform2uiv");
				LOAD_PROC(program_uniform3d, "glProgramUniform3d");
				LOAD_PROC(program_uniform3dv, "glProgramUniform3dv");
				LOAD_PROC(program_uniform3f, "glProgramUniform3f");
				LOAD_PROC(program_uniform3fv, "glProgramUniform3fv");
				LOAD_PROC(program_uniform3i, "glProgramUniform3i");
				LOAD_PROC(program_uniform3iv, "glProgramUniform3iv");
				LOAD_PROC(program_uniform3ui, "glProgramUniform3ui");
				LOAD_PROC(program_uniform3uiv, "glProgramUniform3uiv");
				LOAD_PROC(program_uniform4d, "glProgramUniform4d");
				LOAD_PROC(program_uniform4dv, "glProgramUniform4dv");
				LOAD_PROC(program_uniform4f, "glProgramUniform4f");
				LOAD_PROC(program_uniform4fv, "glProgramUniform4fv");
				LOAD_PROC(program_uniform4i, "glProgramUniform4i");
				LOAD_PROC(program_uniform4iv, "glProgramUniform4iv");
				LOAD_PROC(program_uniform4ui, "glProgramUniform4ui");
				LOAD_PROC(program_uniform4uiv, "glProgramUniform4uiv");
				LOAD_PROC(program_uniform_matrix2dv, "glProgramUniformMatrix2dv");
				LOAD_PROC(program_uniform_matrix2fv, "glProgramUniformMatrix2fv");
				LOAD_PROC(program_uniform_matrix2x3dv, "glProgramUniformMatrix2x3dv");
				LOAD_PROC(program_uniform_matrix2x3fv, "glProgramUniformMatrix2x3fv");
				LOAD_PROC(program_uniform_matrix2x4dv, "glProgramUniformMatrix2x4dv");
				LOAD_PROC(program_uniform_matrix2x4fv, "glProgramUniformMatrix2x4fv");
				LOAD_PROC(program_uniform_matrix3dv, "glProgramUniformMatrix3dv");
				LOAD_PROC(program_uniform_matrix3fv, "glProgramUniformMatrix3fv");
				LOAD_PROC(program_uniform_matrix3x2dv, "glProgramUniformMatrix3x2dv");
				LOAD_PROC(program_uniform_matrix3x2fv, "glProgramUniformMatrix3x2fv");
				LOAD_PROC(program_uniform_matrix3x4dv, "glProgramUniformMatrix3x4dv");
				LOAD_PROC(program_uniform_matrix3x4fv, "glProgramUniformMatrix3x4fv");
				LOAD_PROC(program_uniform_matrix4dv, "glProgramUniformMatrix4dv");
				LOAD_PROC(program_uniform_matrix4fv, "glProgramUniformMatrix4fv");
				LOAD_PROC(program_uniform_matrix4x2dv, "glProgramUniformMatrix4x2dv");
				LOAD_PROC(program_uniform_matrix4x2fv, "glProgramUniformMatrix4x2fv");
				LOAD_PROC(program_uniform_matrix4x3dv, "glProgramUniformMatrix4x3dv");
				LOAD_PROC(program_uniform_matrix4x3fv, "glProgramUniformMatrix4x3fv");
				LOAD_PROC(release_shader_compiler, "glReleaseShaderCompiler");
				LOAD_PROC(scissor_arrayv, "glScissorArrayv");
				LOAD_PROC(scissor_indexed, "glScissorIndexed");
				LOAD_PROC(scissor_indexedv, "glScissorIndexedv");
				LOAD_PROC(shader_binary, "glShaderBinary");
				LOAD_PROC(use_program_stages, "glUseProgramStages");
				LOAD_PROC(validate_program_pipeline, "glValidateProgramPipeline");
				LOAD_PROC(vertex_attrib_l1d, "glVertexAttribL1d");
				LOAD_PROC(vertex_attrib_l1dv, "glVertexAttribL1dv");
				LOAD_PROC(vertex_attrib_l2d, "glVertexAttribL2d");
				LOAD_PROC(vertex_attrib_l2dv, "glVertexAttribL2dv");
				LOAD_PROC(vertex_attrib_l3d, "glVertexAttribL3d");
				LOAD_PROC(vertex_attrib_l3dv, "glVertexAttribL3dv");
				LOAD_PROC(vertex_attrib_l4d, "glVertexAttribL4d");
				LOAD_PROC(vertex_attrib_l4dv, "glVertexAttribL4dv");
				LOAD_PROC(vertex_attrib_l_pointer, "glVertexAttribLPointer");
				LOAD_PROC(viewport_arrayv, "glViewportArrayv");
				LOAD_PROC(viewport_indexedf, "glViewportIndexedf");
				LOAD_PROC(viewport_indexedfv, "glViewportIndexedfv");
				LOAD_PROC(bind_image_texture, "glBindImageTexture");
				LOAD_PROC(draw_arrays_instanced_base_instance, "glDrawArraysInstancedBaseInstance");
				LOAD_PROC(draw_elements_instanced_base_instance, "glDrawElementsInstancedBaseInstance");
				LOAD_PROC(draw_elements_instanced_base_vertex_base_instance, "glDrawElementsInstancedBaseVertexBaseInstance");
				LOAD_PROC(draw_transform_feedback_instanced, "glDrawTransformFeedbackInstanced");
				LOAD_PROC(draw_transform_feedback_stream_instanced, "glDrawTransformFeedbackStreamInstanced");
				LOAD_PROC(get_active_atomic_counter_bufferiv, "glGetActiveAtomicCounterBufferiv");
				LOAD_PROC(get_internalformativ, "glGetInternalformativ");
				LOAD_PROC(memory_barrier, "glMemoryBarrier");
				LOAD_PROC(tex_storage1d, "glTexStorage1D");
				LOAD_PROC(tex_storage2d, "glTexStorage2D");
				LOAD_PROC(tex_storage3d, "glTexStorage3D");
				LOAD_PROC(bind_vertex_buffer, "glBindVertexBuffer");
				LOAD_PROC(clear_buffer_data, "glClearBufferData");
				LOAD_PROC(clear_buffer_sub_data, "glClearBufferSubData");
				LOAD_PROC(copy_image_sub_data, "glCopyImageSubData");
				LOAD_PROC(debug_message_callback, "glDebugMessageCallback");
				LOAD_PROC(debug_message_control, "glDebugMessageControl");
				LOAD_PROC(debug_message_insert, "glDebugMessageInsert");
				LOAD_PROC(dispatch_compute, "glDispatchCompute");
				LOAD_PROC(dispatch_compute_indirect, "glDispatchComputeIndirect");
				LOAD_PROC(framebuffer_parameteri, "glFramebufferParameteri");
				LOAD_PROC(get_debug_message_log, "glGetDebugMessageLog");
				LOAD_PROC(get_framebuffer_parameteriv, "glGetFramebufferParameteriv");
				LOAD_PROC(get_internalformati64v, "glGetInternalformati64v");
				LOAD_PROC(get_object_label, "glGetObjectLabel");
				LOAD_PROC(get_object_ptr_label, "glGetObjectPtrLabel");
				LOAD_PROC(get_program_interfaceiv, "glGetProgramInterfaceiv");
				LOAD_PROC(get_program_resource_index, "glGetProgramResourceIndex");
				LOAD_PROC(get_program_resource_location, "glGetProgramResourceLocation");
				LOAD_PROC(get_program_resource_location_index, "glGetProgramResourceLocationIndex");
				LOAD_PROC(get_program_resource_name, "glGetProgramResourceName");
				LOAD_PROC(get_program_resourceiv, "glGetProgramResourceiv");
				LOAD_PROC(invalidate_buffer_data, "glInvalidateBufferData");
				LOAD_PROC(invalidate_buffer_sub_data, "glInvalidateBufferSubData");
				LOAD_PROC(invalidate_framebuffer, "glInvalidateFramebuffer");
				LOAD_PROC(invalidate_sub_framebuffer, "glInvalidateSubFramebuffer");
				LOAD_PROC(invalidate_tex_image, "glInvalidateTexImage");
				LOAD_PROC(invalidate_tex_sub_image, "glInvalidateTexSubImage");
				LOAD_PROC(multi_draw_arrays_indirect, "glMultiDrawArraysIndirect");
				LOAD_PROC(multi_draw_elements_indirect, "glMultiDrawElementsIndirect");
				LOAD_PROC(object_label, "glObjectLabel");
				LOAD_PROC(object_ptr_label, "glObjectPtrLabel");
				LOAD_PROC(pop_debug_group, "glPopDebugGroup");
				LOAD_PROC(push_debug_group, "glPushDebugGroup");
				LOAD_PROC(shader_storage_block_binding, "glShaderStorageBlockBinding");
				LOAD_PROC(tex_buffer_range, "glTexBufferRange");
				LOAD_PROC(tex_storage2d_multisample, "glTexStorage2DMultisample");
				LOAD_PROC(tex_storage3d_multisample, "glTexStorage3DMultisample");
				LOAD_PROC(texture_view, "glTextureView");
				LOAD_PROC(vertex_attrib_binding, "glVertexAttribBinding");
				LOAD_PROC(vertex_attrib_format, "glVertexAttribFormat");
				LOAD_PROC(vertex_attrib_i_format, "glVertexAttribIFormat");
				LOAD_PROC(vertex_attrib_l_format, "glVertexAttribLFormat");
				LOAD_PROC(vertex_binding_divisor, "glVertexBindingDivisor");
				LOAD_PROC(bind_buffers_base, "glBindBuffersBase");
				LOAD_PROC(bind_buffers_range, "glBindBuffersRange");
				LOAD_PROC(bind_image_textures, "glBindImageTextures");
				LOAD_PROC(bind_samplers, "glBindSamplers");
				LOAD_PROC(bind_textures, "glBindTextures");
				LOAD_PROC(bind_vertex_buffers, "glBindVertexBuffers");
				LOAD_PROC(buffer_storage, "glBufferStorage");
				LOAD_PROC(clear_tex_image, "glClearTexImage");
				LOAD_PROC(clear_tex_sub_image, "glClearTexSubImage");
				LOAD_PROC(bind_texture_unit, "glBindTextureUnit");
				LOAD_PROC(blit_named_framebuffer, "glBlitNamedFramebuffer");
				LOAD_PROC(check_named_framebuffer_status, "glCheckNamedFramebufferStatus");
				LOAD_PROC(clear_named_buffer_data, "glClearNamedBufferData");
				LOAD_PROC(clear_named_buffer_sub_data, "glClearNamedBufferSubData");
				LOAD_PROC(clear_named_framebufferfi, "glClearNamedFramebufferfi");
				LOAD_PROC(clear_named_framebufferfv, "glClearNamedFramebufferfv");
				LOAD_PROC(clear_named_framebufferiv, "glClearNamedFramebufferiv");
				LOAD_PROC(clear_named_framebufferuiv, "glClearNamedFramebufferuiv");
				LOAD_PROC(clip_control, "glClipControl");
				LOAD_PROC(compressed_texture_sub_image1d, "glCompressedTextureSubImage1D");
				LOAD_PROC(compressed_texture_sub_image2d, "glCompressedTextureSubImage2D");
				LOAD_PROC(compressed_texture_sub_image3d, "glCompressedTextureSubImage3D");
				LOAD_PROC(copy_named_buffer_sub_data, "glCopyNamedBufferSubData");
				LOAD_PROC(copy_texture_sub_image1d, "glCopyTextureSubImage1D");
				LOAD_PROC(copy_texture_sub_image2d, "glCopyTextureSubImage2D");
				LOAD_PROC(copy_texture_sub_image3d, "glCopyTextureSubImage3D");
				LOAD_PROC(create_buffers, "glCreateBuffers");
				LOAD_PROC(create_framebuffers, "glCreateFramebuffers");
				LOAD_PROC(create_program_pipelines, "glCreateProgramPipelines");
				LOAD_PROC(create_queries, "glCreateQueries");
				LOAD_PROC(create_renderbuffers, "glCreateRenderbuffers");
				LOAD_PROC(create_samplers, "glCreateSamplers");
				LOAD_PROC(create_textures, "glCreateTextures");
				LOAD_PROC(create_transform_feedbacks, "glCreateTransformFeedbacks");
				LOAD_PROC(create_vertex_arrays, "glCreateVertexArrays");
				LOAD_PROC(disable_vertex_array_attrib, "glDisableVertexArrayAttrib");
				LOAD_PROC(enable_vertex_array_attrib, "glEnableVertexArrayAttrib");
				LOAD_PROC(flush_mapped_named_buffer_range, "glFlushMappedNamedBufferRange");
				LOAD_PROC(generate_texture_mipmap, "glGenerateTextureMipmap");
				LOAD_PROC(get_compressed_texture_image, "glGetCompressedTextureImage");
				LOAD_PROC(get_compressed_texture_sub_image, "glGetCompressedTextureSubImage");
				LOAD_PROC(get_graphics_reset_status, "glGetGraphicsResetStatus");
				LOAD_PROC(get_named_buffer_parameteri64v, "glGetNamedBufferParameteri64v");
				LOAD_PROC(get_named_buffer_parameteriv, "glGetNamedBufferParameteriv");
				LOAD_PROC(get_named_buffer_pointerv, "glGetNamedBufferPointerv");
				LOAD_PROC(get_named_buffer_sub_data, "glGetNamedBufferSubData");
				LOAD_PROC(get_named_framebuffer_attachment_parameteriv, "glGetNamedFramebufferAttachmentParameteriv");
				LOAD_PROC(get_named_framebuffer_parameteriv, "glGetNamedFramebufferParameteriv");
				LOAD_PROC(get_named_renderbuffer_parameteriv, "glGetNamedRenderbufferParameteriv");
				LOAD_PROC(get_query_buffer_objecti64v, "glGetQueryBufferObjecti64v");
				LOAD_PROC(get_query_buffer_objectiv, "glGetQueryBufferObjectiv");
				LOAD_PROC(get_query_buffer_objectui64v, "glGetQueryBufferObjectui64v");
				LOAD_PROC(get_query_buffer_objectuiv, "glGetQueryBufferObjectuiv");
				LOAD_PROC(get_texture_image, "glGetTextureImage");
				LOAD_PROC(get_texture_level_parameterfv, "glGetTextureLevelParameterfv");
				LOAD_PROC(get_texture_level_parameteriv, "glGetTextureLevelParameteriv");
				LOAD_PROC(get_texture_parameter_iiv, "glGetTextureParameterIiv");
				LOAD_PROC(get_texture_parameter_iuiv, "glGetTextureParameterIuiv");
				LOAD_PROC(get_texture_parameterfv, "glGetTextureParameterfv");
				LOAD_PROC(get_texture_parameteriv, "glGetTextureParameteriv");
				LOAD_PROC(get_texture_sub_image, "glGetTextureSubImage");
				LOAD_PROC(get_transform_feedbacki64_v, "glGetTransformFeedbacki64_v");
				LOAD_PROC(get_transform_feedbacki_v, "glGetTransformFeedbacki_v");
				LOAD_PROC(get_transform_feedbackiv, "glGetTransformFeedbackiv");
				LOAD_PROC(get_vertex_array_indexed64iv, "glGetVertexArrayIndexed64iv");
				LOAD_PROC(get_vertex_array_indexediv, "glGetVertexArrayIndexediv");
				LOAD_PROC(get_vertex_arrayiv, "glGetVertexArrayiv");
				LOAD_PROC(get_n_compressed_tex_image, "glGetnCompressedTexImage");
				LOAD_PROC(get_n_tex_image, "glGetnTexImage");
				LOAD_PROC(get_n_uniformdv, "glGetnUniformdv");
				LOAD_PROC(get_n_uniformfv, "glGetnUniformfv");
				LOAD_PROC(get_n_uniformiv, "glGetnUniformiv");
				LOAD_PROC(get_n_uniformuiv, "glGetnUniformuiv");
				LOAD_PROC(invalidate_named_framebuffer_data, "glInvalidateNamedFramebufferData");
				LOAD_PROC(invalidate_named_framebuffer_sub_data, "glInvalidateNamedFramebufferSubData");
				LOAD_PROC(map_named_buffer, "glMapNamedBuffer");
				LOAD_PROC(map_named_buffer_range, "glMapNamedBufferRange");
				LOAD_PROC(memory_barrier_by_region, "glMemoryBarrierByRegion");
				LOAD_PROC(named_buffer_data, "glNamedBufferData");
				LOAD_PROC(named_buffer_storage, "glNamedBufferStorage");
				LOAD_PROC(named_buffer_sub_data, "glNamedBufferSubData");
				LOAD_PROC(named_framebuffer_draw_buffer, "glNamedFramebufferDrawBuffer");
				LOAD_PROC(named_framebuffer_draw_buffers, "glNamedFramebufferDrawBuffers");
				LOAD_PROC(named_framebuffer_parameteri, "glNamedFramebufferParameteri");
				LOAD_PROC(named_framebuffer_read_buffer, "glNamedFramebufferReadBuffer");
				LOAD_PROC(named_framebuffer_renderbuffer, "glNamedFramebufferRenderbuffer");
				LOAD_PROC(named_framebuffer_texture, "glNamedFramebufferTexture");
				LOAD_PROC(named_framebuffer_texture_layer, "glNamedFramebufferTextureLayer");
				LOAD_PROC(named_renderbuffer_storage, "glNamedRenderbufferStorage");
				LOAD_PROC(named_renderbuffer_storage_multisample, "glNamedRenderbufferStorageMultisample");
				LOAD_PROC(read_n_pixels, "glReadnPixels");
				LOAD_PROC(texture_barrier, "glTextureBarrier");
				LOAD_PROC(texture_buffer, "glTextureBuffer");
				LOAD_PROC(texture_buffer_range, "glTextureBufferRange");
				LOAD_PROC(texture_parameter_iiv, "glTextureParameterIiv");
				LOAD_PROC(texture_parameter_iuiv, "glTextureParameterIuiv");
				LOAD_PROC(texture_parameterf, "glTextureParameterf");
				LOAD_PROC(texture_parameterfv, "glTextureParameterfv");
				LOAD_PROC(texture_parameteri, "glTextureParameteri");
				LOAD_PROC(texture_parameteriv, "glTextureParameteriv");
				LOAD_PROC(texture_storage1d, "glTextureStorage1D");
				LOAD_PROC(texture_storage2d, "glTextureStorage2D");
				LOAD_PROC(texture_storage2d_multisample, "glTextureStorage2DMultisample");
				LOAD_PROC(texture_storage3d, "glTextureStorage3D");
				LOAD_PROC(texture_storage3d_multisample, "glTextureStorage3DMultisample");
				LOAD_PROC(texture_sub_image1d, "glTextureSubImage1D");
				LOAD_PROC(texture_sub_image2d, "glTextureSubImage2D");
				LOAD_PROC(texture_sub_image3d, "glTextureSubImage3D");
				LOAD_PROC(transform_feedback_buffer_base, "glTransformFeedbackBufferBase");
				LOAD_PROC(transform_feedback_buffer_range, "glTransformFeedbackBufferRange");
				LOAD_PROC(unmap_named_buffer, "glUnmapNamedBuffer");
				LOAD_PROC(vertex_array_attrib_binding, "glVertexArrayAttribBinding");
				LOAD_PROC(vertex_array_attrib_format, "glVertexArrayAttribFormat");
				LOAD_PROC(vertex_array_attrib_i_format, "glVertexArrayAttribIFormat");
				LOAD_PROC(vertex_array_attrib_l_format, "glVertexArrayAttribLFormat");
				LOAD_PROC(vertex_array_binding_divisor, "glVertexArrayBindingDivisor");
				LOAD_PROC(vertex_array_element_buffer, "glVertexArrayElementBuffer");
				LOAD_PROC(vertex_array_vertex_buffer, "glVertexArrayVertexBuffer");
				LOAD_PROC(vertex_array_vertex_buffers, "glVertexArrayVertexBuffers");
				return true;
			}
			#undef LOAD_PROC
		}

		#undef DEFINE_API
	}
	using namespace funcs;
	namespace loader
	{

		bool load()
		{
			return load_core();
		}


	}
	using namespace loader;
}

